### ISSUE TITLE
Issue with DBBACKUP_BACKUP_DIRECTORY

### ISSUE THREAD

**Issue by psychok7** [django-dbbackup/django-dbbackup#100]
HI there, i am getting a `CommandError: Filesystem storage requires DBBACKUP_BACKUP_DIRECTORY to be defined in settings` in the Master branch but the thing is i have the `DBBACKUP_BACKUP_DIRECTORY` in my settings file.

I think this is related to https://github.com/django-dbbackup/django-dbbackup/pull/93 but i am not sure how can i fix this.. any ideas?

**Comment by ZuluPro** [comment]
Are you using master version ?
I'm looking this very soon.

**Comment by psychok7** [comment]
@ZuluPro yes the master branch that i just pulled a few hours ago. I stumbled upon this when i was trying to test this patch i wrote https://github.com/django-dbbackup/django-dbbackup/issues/100

**Comment by ZuluPro** [comment]
When do you see this error message? What do you try to launch ?

**Comment by psychok7** [comment]
@ZuluPro when i try to `python manage.py dbrestore --settings=something`

**Comment by ZuluPro** [comment]
Do you have a warning, for deprecated this setting. Can you give a sample of your settings?

**Comment by psychok7** [comment]
@ZuluPro these are my dbbackup settings:

```
DBBACKUP_BACKUP_DIRECTORY = os.path.join(BASE_DIR, 'pap_management/backups/')
DBBACKUP_CLEANUP_KEEP = 1
DBBACKUP_CLEANUP_KEEP_MEDIA = 1
```

**Comment by ZuluPro** [comment]
It should be fixed with this new commit.
We make a bad action with this line: https://github.com/django-dbbackup/django-dbbackup/commit/f0bd4ee83d86ee6ceb525a9f84d5d895fbfed83c#diff-81c0ec47914253dcbaf03c1bf7eecbd3L22

I remove it and add more tests for the storage check.

**Comment by psychok7** [comment]
ok i will test the new commit in a few hours as well as my code in the other PR

**Comment by ZuluPro** [comment]
@psychok7: I've made this commit for fix your issue: https://github.com/ZuluPro/django-dbbackup/commit/9b9f2c30d946dda4944dcb70441f177f360b2905

Effectively, how was the code we didn't use the storage options in commands (but yes in unit tests ...)
Can you pull this branch and test it ?

You can make: ``git pull --rebase git@github.com:ZuluPro/django-dbbackup.git issue_100``
For merge my changes in your branch without make a merge.

**Comment by psychok7** [comment]
@ZuluPro `git pull --rebase git@github.com:ZuluPro/django-dbbackup.git issue_100` seems to work fine. No more errors or warnings. ;)

**Comment by ZuluPro** [comment]
Ok thanks, I merge it soon as possible.

**Comment by ZuluPro** [comment]
Fix merged, I close this ticket.
