### ISSUE TITLE
Remake DBcommand system

### ISSUE THREAD

**Issue by ZuluPro** [django-dbbackup/django-dbbackup#102]
I think ``dbbackup.dbcommands`` need to be refactored. It is really painful to work with it, understand, configure and imagine make oneself a new engine.

We should make this simpler like storage API. A simple class with followings methods which must be implemented:
- create_backup
- restore_backup

Example:
```
class SqliteConnector(BaseConnector):
    def create_backup(self):
        make_it()

    def restore_backup(self, inputfile):
        resotre(inputfile)
```

I started to make an example of this concept SQLite and I can make several comments:
- It's so easy to deal with only one simple class inherited
- I use built-in Django connection for Sqlite but Popen can be used to create dump

@benjaoming, @mjs7231, @others, What do you think about it ?

**Comment by ZuluPro** [comment]
My tests are foundable here: https://github.com/ZuluPro/django-dbbackup/tree/dbconnector

**Comment by benjaoming** [comment]
@ZuluPro looking at the test, I get a feeling that you are trying to replace conventional dump and restore tools? Is that so or am I misunderstanding the intentions?

**Comment by ZuluPro** [comment]
@benjaoming, pgdump and mysqldump, no.
But with sqlite there is ``sqlite3.dump._iterdump`` but it dumps table without `ÌF NOT EXISTS``. So I rewrite it.

My intention is more to make more simple backup manager, even it uses ``os.system``.

**Comment by ZuluPro** [comment]
@benjaoming @mjs7231,
Maybe I don't (yet) understand everything but I tested to:
1. Create a model instance
2. Make a backup
3. Delete model instance
4. Make backup restore
5. Test existence
And it failed. I maybe miss something in my conf but I think we should really re-factor this system for make it simplier

**Comment by benjaoming** [comment]
@ZuluPro, be careful if this is a unit test case... those always wrap transactions, so a database restore won't be visible from within a transaction that you've started before the restore.

**Comment by ZuluPro** [comment]
@benjaoming @mjs7231 
I worked again on connectors here [dbconnector branch](https://github.com/ZuluPro/django-dbbackup/commits/dbconnector)

I made:
- ``SqliteConnector``: Create SQL dump in by inspecting tables
- ``SqliteCPConnector``: Just copy SQLite binary file
- ``MysqlDumpConnetor``: Make MySQL dump with ``mysqldump``
- ``PgDumpConnetor``: Make PostgreSQL dump with ``pg_dump``
- ``MongoDumpConnetor``: Make MongoDB dump with ``mongodump``

I added a ``DBBACKUP_CONNECTORS`` setting (maybe the name is inappropriate), it can be used to override `DATABASES` settings and add some specific ones to connectors. example we have in settings:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'USER': 'mydatabaseuser',
        'NAME': 'mydatabase',
    },
}
DBBACKUP_CONNECTORS = {
    'default': {
        'USER': 'mybackupuser',
        'PASSWORD': 'mybackuppassword',
    },
}
```

That will allow to reuse easily database settings and include extended configuration.

Do you think I'm going in the right direction ?

**Comment by benjaoming** [comment]
Looks really promising, I agree that this is a much better approach. I think you need a mapping for postgis.

Other than that, it's hard to give input without a PR. I tried looking around a bit, and I think it's looking good.

But the big question is: How does it affect existing installations? Is it backwards 100% compatible? Will people be able to do `pip install django-dbbackup --upgrade` and nothing breaks?

**Comment by ZuluPro** [comment]
@benjaoming Thank you very much for your feedback.

Don't you think `USE_POSTGIS` in connector configuration is sufficient ?

I'm going to create a WIP PR for this.

I don't finish to make 100% backward compatibility, I need some help for make real tests with all database connectors. Actually SQLite will work with SqliteCPConnector, not sure but it's the same approach. I would like to add Travis tests for all DB backend backup and backward compatibility.

**Comment by ZuluPro** [comment]
@benjaoming:
As you ask, I made this PR #165 for work together.
