### ISSUE TITLE
dbbackup error if SQL server parameters only referenced in settings.py file

### ISSUE THREAD

**Issue by ajtaylor6** [django-dbbackup/django-dbbackup#122]
The application I'm working with keeps the DB connection variables in a seperate file which is then referenced within settings.py as seen below
```
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'OPTIONS': {
                'init_command': 'SET storage_engine=INNODB',
                'read_default_file':os.path.join(BASE_DIR,'my.conf'),
            },
        }
    }
```
This works well for all other Django purposes, however when running the "dbbackup" command, django-dbbackup can't seem to find the variables stored there and errors out with the command below:
```
(venv)user@host:/webapps/$ python3 manage.py dbbackup    
Backing Up Database: 
****** ****** ******R******u******n******n******i******n******g******:****** ******m******y******s******q******l******d******u******m******p****** ******-******-******u******s******e******r******=****** ******-******-******p******a******s******s******w******o******r******d******=****** ******
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect
CommandError: Error running: ['mysqldump', '--user=', '--password=', '']
```

Is there a way to reference the variables after they are read through the settings.py file and available for use?

**Comment by ZuluPro** [comment]
It an dbbackup's internal issue, we shouldn't get databases description from `django.conf.settings` but other after django project's setup.
I'll take a look a soon as possible.

**Comment by TristanSmithlib** [comment]
I had the same issue but I discovered that the setting "read_default_file" is specific to the MySQL engine. Perhaps a more universal approach to separating the sensitive info (that is also compatible with django-dbbackup) is to have a base settings file which is tracked in version control and a private settings file which is not tracked in version control, but which imports all the settings from the base file. Like this:

settings_base.py (tracked)

``` python
# Main settings

.
.
.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    .
    .
    .
]
.
.
.

```

settings.py (untracked)

``` python
from .settings_base import *

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mydb',
        'USER': 'myuser',
        'PASSWORD': 'opensesame',
    }
}

```

On a given environment (local, dev, stage, prod, etc) you would create a new untracked settings.py which extends the base settings file but has system specific (and secret) configurations.

This worked for me! Now I can have an untracked secrets file and also use django-dbbackup.
