### ISSUE TITLE
FILENAME_TEMPLATE bug if callable

### ISSUE THREAD

**Issue by pacahon** [django-dbbackup/django-dbbackup#132]
Hello. My settings:
```
DBBACKUP_MEDIA_FILENAME_TEMPLATE = backup_filename  # callable
```
Debug `locals()`:
```
'MEDIA_FILENAME_TEMPLATE': <function backup_filename at 0x7effe662ec80>,
```
Part of traceback:
```
...
 File "/home/test/env/local/lib/python2.7/site-packages/dbbackup/settings.py", line 115, in <module>
    if '{%s}' % param not in locals()[sett]:
TypeError: argument of type 'module' is not iterable
```

 The problems lies [here](https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/settings.py#L112).

**Comment by ZuluPro** [comment]
Ok thanks for create this issue !
I'll check this tonight.

**Comment by ZuluPro** [comment]
@pacahon : Is it still relevant ?

**Comment by pacahon** [comment]
@ZuluPro I haven't callable *_FILENAME_TEMPLATE now, but I'm sure your commit fixed topics issue, thx.
