### ISSUE TITLE
dbrestore/listbackups not working

### ISSUE THREAD

**Issue by ManuelGysin** [django-dbbackup/django-dbbackup#137]
Hello

I use the following configuration:

- Postgres
- Amazon S3
- Location setting to wrote into sub folder in the bucket

Use case:
- Running dbbackup creates a backup on s3 at the right path
- Running dbrestore tells me no backup found
- Running listbackups returns an empty list

Greets
Manuel

**Comment by ZuluPro** [comment]
Ok thanks for opening an issue.
I'll look deeper tonight.

**Comment by ZuluPro** [comment]
@ManuelGysin: Can you give me the name of the created backup file ?

**Comment by ManuelGysin** [comment]
@ZuluPro 

Names:
- roaf-06a89838ff48-2015-12-15-221831.psql
- roaf-398ed47fe9b3-2015-12-15-200228.psql

Settings:

DBBACKUP_STORAGE = 'dbbackup.storage.s3_storage'                                                                                                                                                                                                                                            
DBBACKUP_STORAGE_OPTIONS = {                                                                                                                                                                                                                                                                
    'access_key': 'replaced',                                                                                                                                                                                                                                                   
    'secret_key': 'replaced',                                                                                                                                                                                                                               
    'bucket_name': 'some-backup-bucket',                                                                                                                                                                                                                                                            
    'location': 'ROAF-UNSPECIFIED'                                                                                                                                                                                             
}

**Comment by ManuelGysin** [comment]
Can be closed after merge with #139

**Comment by ZuluPro** [comment]
@ManuelGysin Can you give me the file's names generated by dbbackup.
