### ISSUE TITLE
Security issue through django-storag-redux default permissions on S3

### ISSUE THREAD

**Issue by ManuelGysin** [django-dbbackup/django-dbbackup#142]
There seems a more or less huge issue with the permissions on the backups files on S3. Uploaded backup files are getting an extra permission with open/download for everyone:

![permissions](https://cloud.githubusercontent.com/assets/2873373/12079882/70e2ceb4-b249-11e5-9b80-09e1c223e287.png)

As you can see, if the link can be predicted or brute forced, everyone is able to get the backup files.

If you are not using encryption this is a security nightmare for sensitive user data.
Please adjust the permissions on the backup files when created and uploaded in django-dbbackup and add documentation that there is a security problem with older backups and wrong permissions.

Kind regards
Manuel Gysin

* This issue was pre-discussed per email

**Comment by ZuluPro** [comment]
I found how to fix your trouble:

In Django Storages you can set the following parameters for set ACL:
- `AWS_DEFAULT_ACL`: By default `'public-read'` (<--- This is your problem)
- `AWS_BUCKET_ACL`: By default `AWS_DEFAULT_ACL`

You can find all ACL and their definitions here: http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

**Comment by ZuluPro** [comment]
We should also change the default policy and add a warning on DBBackup's docs.

**Comment by ManuelGysin** [comment]
AWS_DEFAULT_ACL: 'public-read' is not bad at all, because you can serve static/media files over S3. Because of this I disagree to change this, but you gave a perfect solution in DBBACKUP_STORAGE_OPTIONS. I just overwrote 'default_acl' and now backups are secured.

+1 for printing a warning, I suggest to set 'default_acl': 'private' in DBBACKUP_STORAGE_OPTIONS as default.

DBBACKUP_STORAGE_OPTIONS = {                                                                                                                                                                                
    'access_key': os.environ.get("APP_BKP_KEY", ""),                                                                                                                                                        
    'secret_key': os.environ.get("APP_BKP_SECRET", ""),                                                                                                                                                     
    'bucket_name': os.environ.get("APP_BKP_BUCKET", ""),                                                                                                                                                    
    'location': 'ROAF-' + os.environ.get("APP_BKP_LOCATION", ""),                                                                                                                                           
    'default_acl': 'private'                                                                                                                                                                                
}

Thanks for the fast response time :)

**Comment by ZuluPro** [comment]
This issue can be closed with this merged PR #155
