### ISSUE TITLE
PostgreSQL output file and compress functionality

### ISSUE THREAD

**Issue by eriktelepovsky** [django-dbbackup/django-dbbackup#143]
Hi, right now, the output of the backup file is the plain text sql format. It is not very storage efficient. For postgres `pg_dump` command offers output format selection:

```
$ man pg_dump
```

```
...
-F format
       --format=format
           Selects the format of the output.  format can be one of the following:

           p
           plain
               Output a plain-text SQL script file (the default).

           c
           custom
               Output a custom-format archive suitable for input into pg_restore. Together with the directory output format, this is the most flexible output format in that it allows
               manual selection and reordering of archived items during restore. This format is also compressed by default.
...
```

I tried it and the output .pg file is about 15-20x smaller then the default .sql script file because of automatic compression. Except of that, the backuping process is much more faster and better for restoring because it is suitable for pg_restore command. It comes with many useful arguments like `--table`, `--data-only`, etc... 

I believe it should be set as default output format for PostgreSQL.

**Comment by ZuluPro** [comment]
Thanks for this issue @eriktelepovsky .
Effectively we should use PostgreSQL compression by default, but we should warn user to not compress again with DBBackup.

**Comment by GeoffThorpeFT** [comment]
Is this 'question' going to be converted into an issue?

I think it is an issue that we are not able to define whether compression is to be used.

**Comment by ZuluPro** [comment]
@GeoffThorpeFT Sorry for our latency
We plan to remake the DBCommand system (cf: #102), this enhancement is made for deal better with all options of backup systems.
Unfortunately, time is missing...

This issue is really pertinent and not considered only as question.
