### ISSUE TITLE
Allowing backup and restore from filepath

### ISSUE THREAD

**Issue by MickaelBergem** [django-dbbackup/django-dbbackup#146]
I am using Ansible to trigger dbbackup and retrieve locally the backups. Until now I was using the 2.0.4 version, which was creating a backup at `default.backup` in the current directory.
Now I want to upgrade to the last version (2.3.3) to use `dbrestore`'s `-noinput` flag from Ansible, but I am not able to force the creation at an exact filename. I don't want to use any timestamp inside the name in order to retrieve the file easily, but using ```DBBACKUP_FILENAME_TEMPLATE = '{servername}.{extension}'
``` gives the following error:

```
  File "/var/www/geoponts-dev.local/env/lib/python3.4/site-packages/dbbackup/management/commands/dbbackup.py", line 17, in <module>
    from ...dbcommands import DBCommands, MongoDBCommands
  File "/var/www/geoponts-dev.local/env/lib/python3.4/site-packages/dbbackup/dbcommands.py", line 17, in <module>
    from dbbackup import (settings, utils)
  File "/var/www/geoponts-dev.local/env/lib/python3.4/site-packages/dbbackup/settings.py", line 117, in <module>
    raise ImproperlyConfigured(msg)
django.core.exceptions.ImproperlyConfigured: You must provide '{datetime}' in DBBACKUP_FILENAME_TEMPLATE
```

I don't want to try to guess the correct datetime from Ansible.
How can I achieve this? Is there a feature to backup the db under a given name like `python manage.py dbbackup --backup-filename=default.backup`?

Thanks!

PS: I was not able to add the label "question" to this ticket...

**Comment by ZuluPro** [comment]
Thanks for opening this issue.

We forced timestamp in ``DBBACKUP_FILENAME_TEMPLATE``, but we thought it will disable some use cases. I will make some patch for allow the following topics:
- Backup to a particular path on filesystem or storage
- Restore from a particular file on filesystem or storage

I'll make it as soon as possible !

Otherwise, how do you use Ansible with dbbackup ?
I though a dbbackup module could be a great thing.

**Comment by MickaelBergem** [comment]
Hello Anthony, thank you for the quick response!

Here is my playbook to backup and retrieve locally all the databases:

    ---
    # DB Backup
    #
    # To retrieve the (encrypted) backup of the database of every webserver:
    #   ansible-playbook dbbackup.yml

    - name: Sauvegarde de la base de données
      hosts: "{{ 'vagrantbox' if vagrant|default(False) == True else 'web' }}"
      remote_user: "{{ user_python }}"
      vars_files:
        - vars/defaults.yml
        - vars/instances/{{ instance_id }}.yml

      tasks:
        - name: Backup the database
          django_manage:
            command="dbbackup --encrypt"
            settings=myapp.settings_prod
            app_path=/var/www/{{ dirname }}
            virtualenv=/var/www/{{ dirname }}/env

        - name: Retrieve the backup locally
          fetch:
            src=/var/www/{{ dirname }}/default.backup
            dest=backups/{{ ansible_hostname }}/{{ ansible_date_time['iso8601'] }}.backup
            flat=yes
            fail_on_missing=yes

Using the `django_manage` module of Ansible is simple enough I think, there is no need to create a new one (at least for my usage).

I'm looking forward to seeing the new version of django-dbbackup! :)

**Comment by ZuluPro** [comment]
Hello @MickaelBergem,
Could you confim me this patch make what you want :
https://github.com/ZuluPro/django-dbbackup/tree/cmd_options

**Comment by MickaelBergem** [comment]
Hello @ZuluPro, thanks for the patch!

This is what I did:

```
$ pip install git+git://github.com/ZuluPro/django-dbbackup/@cmd_options
$ python manage.py dbbackup -o /var/www/backups/test.backup
[...]
dbbackup.storage.base.StorageError: Filesystem storage requires DBBACKUP_STORAGE_OPTIONS["location"] to be defined in settings.
```

Hmm yeah even if I want to backup to a given path I need to configure this... It may be nice to disable these checks if we don't use it. Second try:

```
$ python manage.py dbbackup -o kikoo
Backing Up Database: /home/suixo/Projets/aaa/db.sqlite3
Reading: /home/suixo/Projets/aaa/db.sqlite3
Backup tempfile created: 3.5 MB
Writing file to FileSystemStorage: <bound method Storage.backup_dir of <dbbackup.storage.filesystem_storage.Storage object at 0x7ffba4a6efd0>>, filename: kikoo
Writing file kikoo
Writing file kikoo
```

It is worth noting that the path specified in `DBBACKUP_STORAGE_OPTIONS["location"]` restricts the possible export filepath: 

```django.core.exceptions.SuspiciousFileOperation: The joined path (/home/suixo/kikoo) is located outside of the base path component (/home/suixo/Projets/aaa)```

It is a good start but may be improved if you have time :)

**Comment by ZuluPro** [comment]
Hello @MickaelBergem,
I also added ``-O | --output-path`` for specify an output anywhere on filesystem.

Could you confirm that fix your trouble ?

**Comment by MickaelBergem** [comment]
@ZuluPro I may do something the wrong way but it looks like the file is not created:

    $ python manage.py dbbackup -O /tmp/teest && file /tmp/teest
    Backing Up Database: /home/suixo/Projets/aaa/db.sqlite3
    Reading: /home/suixo/Projets/aaa/db.sqlite3
    Backup tempfile created: 4.0 MB
    Writing file to _home_suixo_Projets_aaa_db.sqlite3-mickael-buzz-2016-03-06-152954.sqlite
    /tmp/teest: empty

The created file `/tmp/teest` is indeed empty...

**Comment by ZuluPro** [comment]
Oops, I forgot to ``seek(0)``before copy the file. Could you test again ?

**Comment by MickaelBergem** [comment]
I just tested, that's perfect! :)

Any idea on when the next official release containing this feature will get deployed?

**Comment by ZuluPro** [comment]
Fine !
I will be deployed as soon as possible, I just wait an another bugfix
confirmation.

**Comment by ZuluPro** [comment]
Hello @MickaelBergem, New DBBackup version is available ! Sorry for my latency.
