### ISSUE TITLE
TypeError: environment can only contain strings

### ISSUE THREAD

**Issue by vaibhav-jain** [django-dbbackup/django-dbbackup#147]
I am getting this error http://stackoverflow.com/questions/34557822/typeerror-environment-can-only-contain-strings

Can you tell me how to resolve this error??

**Comment by ZuluPro** [comment]
Hello, Thank for report this issue.

Can you tell us:
- Your Python version
- Django version
- Dbbackup version

And also describe how the bug appears ?

**Comment by vaibhav-jain** [comment]
Hi,
Django (1.7)
Python (2.7.6)
django-dbbackup (2.3.3)

**Comment by ZuluPro** [comment]
I think you have a bad location: ``r'D:/backup'``

Can try other way ? There's no benefit of use raw string with ``/``.
What about:
- ``r'D:\backup'``
- ``'D:/backup'``

**Comment by vaibhav-jain** [comment]
Already did  . . .  But issue is related to this https://mail.python.org/pipermail/python-win32/2010-April/010400.html

**Comment by mjs7231** [comment]
This doesn't look like a django-dbbackup error, but a subprocess or environment error on your system. I suspect *any* subprocess call on your system would result in the same error. If you keep reading the thread posted in your python mailing list thread, [you can see the guy solved it by forcing his environment variables from unicode to strings](https://mail.python.org/pipermail/python-win32/2010-April/010403.html).

I'm going to close this issue, but feel free to reopen it if you feel this is a django-dbbackup specific error.
