### ISSUE TITLE
Error while Django Database Backup - AttributeError: 'NoneType' object has no attribute 'extension'

### ISSUE THREAD

**Issue by royki** [django-dbbackup/django-dbbackup#148]
I am trying to use [django-dbbackup v2.3.3][1] to backup the database of django project (`django-1.8.4`, `python - 3.4.3`)

I am following this [django-dbbackup][2] documentation.

Below is my project settings for **DATABASES** and **DATABASE_BACKUP**

    INSTALLED_APPS = (
        'django.contrib.auth',
        'django_admin_bootstrapped',
        'django.contrib.admin',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.contrib.gis',

        'authtools',
        'crispy_forms',
        'easy_thumbnails',
        'rest_framework',
        'dbbackup',

        'profiles',
        'location',
        'maps'

    )

    DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.spatialite'

    # DATABASE BACKUP SETTINGS
    DBBACKUP_STORAGE = 'dbbackup.storage.filesystem_storage'
    DBBACKUP_STORAGE_OPTIONS ={'location':'/home/altius/locateme/src/backup/'}

And I am getting the following error -

    Backing Up Database: db.sqlite3
    Traceback (most recent call last):
       File "manage.py", line 13, in <module>
         execute_from_command_line(sys.argv)
       File"/usr/local/lib/python3.4/distpackages/django/core/management/__init__.py", line 338, in execute_from_command_line
         utility.execute()
       File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
       File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
       File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
       File "/usr/local/lib/python3.4/dist-packages/dbbackup/utils.py", line 100, in wrapper
    func(*args, **kwargs)
       File "/usr/local/lib/python3.4/dist-packages/dbbackup/management/commands/dbbackup.py", line 54, in handle
    self.save_new_backup(database)
       File "/usr/local/lib/python3.4/dist-packages/dbbackup/management/commands/dbbackup.py", line 66, in save_new_backup
    filename = self.dbcommands.filename(self.servername)
       File "/usr/local/lib/python3.4/dist-packages/dbbackup/dbcommands.py", line 278, in filename
    extension = self.settings.extension
    AttributeError: 'NoneType' object has no attribute 'extension'

I tried to look into other errors but in vain to find out the solution for 
 **AttributeError: 'NoneType' object has no attribute 'extension'** 

There are several **AttributeError** like `append`, `strip`, `format` etc. but not able to find **extension** error. 

Am I missing some more settings ? What else  need to do to get rid of this error to backup the database locally for django-project ?

Stackoverflow Question - [SO][3]
One answer from [SO][3], I would likely to ask as I am using `SpatiaLite` with `Sqlite3`. Does `django-dbbackup` support the  `SpatiaLite` library for Sqlite3. Is this the reason to get this error. What is the solution ?
  [1]: https://pypi.python.org/pypi/django-dbbackup/2.3.3
  [2]: http://django-dbbackup.readthedocs.org/en/latest/storage.html#local-disk
  [3]:http://stackoverflow.com/questions/34856546/error-while-django-database-backup-attributeerror-nonetype-object-has-no-at

**Comment by mjs7231** [comment]
We don't support SpatiaLite. it sounds like spatialite is just an enhanced form of sqlite3? I know nothing about it and would have to leave the testing of that up to you.

That said, and assuming you could backup SpatiaLite in the same ways you backup sqlite3. Try this for starters. Look at `dbcommands .py:240 in the function _get_settings()`. You may be able to add `spatialite` to the section that looks up the sqlite3 settings and go form there.

**Comment by mjs7231** [comment]
I also made change 1e00b9b5 to raise a better error message when we have an unknown db engine.

**Comment by ZuluPro** [comment]
@royki : Is this issue still relevant ?

**Comment by royki** [comment]
We changed to PostgreSQL.

**Comment by ZuluPro** [comment]
Spatialite is now supposed to be supported with #165
