### ISSUE TITLE
Incorrect Documentation.

### ISSUE THREAD

**Issue by mjs7231** [django-dbbackup/django-dbbackup#15]
I have set up Django dbbackup for a posgres database..
your documentation states that you can set
DBBACKUP_POSTGRES_BACKUP_COMMANDS (optional) List of commands to use execute when creating a backup. Commands are sent to popen and should be split into shlex tokens. By default, the following command is run: >> pg_dump --username={adminuser} --host={host} --port={port} {databasename} >
DBBACKUP_POSTGRES_BACKUP_COMMANDS is the wrong setting variable used for documenting.. After going through the code i found 'DBBACKUP_POSTGRESQL_BACKUP_COMMANDS' is what is used in code.

**Comment by dimka665** [comment]
Docs doesn't explain
DBBACKUP_POSTGRE**SQL**_BACKUP_COMMANDS or DBBACKUP_POSTGRE**S**_BACKUP_COMMANDS
now.

**Comment by eriktelepovsky** [comment]
+1

I would like to add -Fc argument for pg_dump. How could it be done using ``DBBACKUP_POSTGRESQL_BACKUP_COMMANDS`` setting? Is it possible?

**Comment by eriktelepovsky** [comment]
Can somebody explain me how to use custom backup command setting? I don't understand it.

**Comment by ZuluPro** [comment]
Retification, we should really refactor dbcommands...

**Comment by laurendw** [comment]
Documentation on how to use POSTGRESQL_RESTORE_COMMANDS would be really useful as well.

**Comment by ZuluPro** [comment]
Documentation in progress here: https://github.com/ZuluPro/django-dbbackup/tree/docs
It will be for V3
