### ISSUE TITLE
Docs on RTD are outdated and won't build

### ISSUE THREAD

**Issue by jjkester** [django-dbbackup/django-dbbackup#154]
The docs as published on Read the Docs are outdated. However, it is not possible to build the latest version of the docs. Read the Docs just gives the error "Failed".

**Comment by ZuluPro** [comment]
Thanks, I'm looking at this.

**Comment by ZuluPro** [comment]
Doc updated : http://django-dbbackup.readthedocs.org/en/latest/

Thanks for this issue.
