### ISSUE TITLE
Dropbox backup path

### ISSUE THREAD

**Issue by uramonz** [django-dbbackup/django-dbbackup#156]
Hi,

Is there a way to setup/specify the file destination path when using Dropbox backup mode? Right now just drops the file in app folder root, I need to have my backups in a separate folder like MyApp/Backups

Thanks and congratulations for this project!

**Comment by ZuluPro** [comment]
Hello @uramonz 
Thanks for open this issue and sorry for my latency

As explained in PR #146, the next version of DBBackup will allow to save and restore anywhere on file system or on storage (Dropbox or whatever).
You'll be able to make:
```
./manage.py dbbackup -O my/path/on/dropbox
./manage.py dbrestore -I my/path/on/dropbox
```

This next version will be deployed on Pypi this weekend (I hope).
You can already try this feature by install the version in master branch.

**Comment by uramonz** [comment]
Great!! Thanks for your reply

**Comment by ZuluPro** [comment]
Hello @uramonz, New DBBackup version is available !
