### ISSUE TITLE
DBBACKUP_MEDIA_FILENAME_TEMPLATE not working

### ISSUE THREAD

**Issue by celiao** [django-dbbackup/django-dbbackup#158]
If I search this repository for `MEDIA_FILENAME_TEMPLATE`, I see that it gets assigned to `DBBACKUP_MEDIA_FILENAME_TEMPLATE`, as expected.  However, that's the only occurrence. `MEDIA_FILENAME_TEMPLATE` is not used anywhere and the functionality to set the media filename template doesn't work.

**Comment by ZuluPro** [comment]
@celiao Thank you very much for this issue, I will take care as soon as possible. Does it block you in your DBBackup usage ?

**Comment by celiao** [comment]
@ZuluPro Thanks for your quick response.  This doesn't block my usage.  It just makes it more difficult to distinguish between DB and MEDIA files in my backup directory.  In my `settings.py` file, I would like to set: `DBBACKUP_MEDIA_FILENAME_TEMPLATE = 'media-{servername}-{datetime}.{extension}'`.
