### ISSUE TITLE
dbrestore --backup-extension not working

### ISSUE THREAD

**Issue by celiao** [django-dbbackup/django-dbbackup#159]
In my backup directory, I have files that end with `.psql` (database) and `.tar.gz` (media).  The newest file is a `.tar.gz` file.  Unfortunately, when I execute `python manage.py dbrestore`, it tries to restore the `.tar.gz` file as the database file.

I also tried `python manage.py dbrestore --backup-extension psql` and `python manage.py dbrestore --backup-extension .psql`, to no avail.

It would be great if `--backup-extension` worked, or if we could store the media files in a different backup location, e.g., `DBBACKUP_STORAGE_OPTIONS = {'location': 'backups/db', 'location_media': 'backups/media'}`.

**Comment by ZuluPro** [comment]
I implemented command options for choose exactly the file to backup. Is it useful for you ?

Otherwise, Let the possibility to store media in another storage seems to be a great feature.

**Comment by celiao** [comment]
The documentation says the option for specifying a file to restore is `-f`, but that produces the error: `manage.py: error: no such option: -f`.

Later, I looked at the code, and discovered the option actually is `-i` or `--input-filename`, which works and is helpful.

It would be nice to have `--backup-extension` working, since it's in the documentation.

Also, adding the `location_media` specification would cleanup the backup directory.

**Comment by ZuluPro** [comment]
Hello @celiao, is your issue is still relevant ?

**Comment by celiao** [comment]
I was able to work around my issue with `--input-filename`.

I'd still recommend, if not done already:
- Fixing `--backup-extension`
- Adding a constant like `DBBACKUP_STORAGE_OPTIONS`

**Comment by ZuluPro** [comment]
@celiao , No worries next version will entirely fix it (https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/db/base.py#L44)

**Comment by ZuluPro** [comment]
@celiao 
As written a lot a change has been made:

``--backup-extension`` has been removed from DBBackup.
All database engines have their own extension and you customize it with ``settings.CONNECTORS['dbname']['extension']``

More deeply in code, you had this issue because of a bad filtering of files which is now fixed.

Does it satisfy you ?
