### ISSUE TITLE
Error when backup postgresql without username

### ISSUE THREAD

**Issue by mjs7231** [django-dbbackup/django-dbbackup#16]
In my settings I have:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2', 
            'NAME': 'abc',                     
            'USER': '',
            'PASSWORD': '',
            'HOST': '',                  
            'PORT': '',                  
        }

my application works and my postgres server is on 127.0.0.1 and my postgres use IDENT authentication.
if I configure dbbackup as explained, and run:
``django-admin.py dbbackup``
I get the following error:
```
pg_dump: [archiviatore (db)] connessione al database "abc" fallita: FATALE: nessun utente PostgreSQL specificato nel pacchetto di avvio CommandError: Error running: ['pg_dump', '--username=', '<myusername>']
```
which is the italian for the error:
``pg_dump: [archiver (db)] connection to database "abc" failed: FATAL: no PostgreSQL user name specified in startup packet``
I guess the problem is that in this configuration the Command executed should be just:
``pg_dump``
(which, btw, works if run via CLI).
Am I right? Is it possible to fix it? If you want, I can try to look for the place in the code that builds the command line and try to fix it.

**Comment by ZuluPro** [comment]
I don't think this issue come from dbbackup.
It seems you only not configure the user.

**Comment by benjaoming** [comment]
@ZuluPro you can authorize postgres without a username through unix sockets + PAM. This is a conventional way that avoids having passwords in files.

The issue is legit, the whole --username shouldn't be added to CLI when it's unset.

**Comment by ZuluPro** [comment]
Yes I though the same thing, it shouldn't be set if unused.

**Comment by ZuluPro** [comment]
Closed with dbconnector system.
