### ISSUE TITLE
Question about memory issue

### ISSUE THREAD

**Issue by raratiru** [django-dbbackup/django-dbbackup#160]
Executing the django command ```./manage.py loaddata``` I receive an interruption with the following message: ```killed```

I assume that this is a memory issue since my server is running on 512MB and the basic database json file is 50MB. 

Is ```django-backup``` able to perform the backup and restore operations successfully in this environment?

**Comment by ZuluPro** [comment]
We have some memory issues, but as DBbackup uses SpooledTemporaryFile we avoid to fill RAM.
Otherwise if you don't use compression or encryption, you shouldn't have trouble.

**Comment by raratiru** [comment]
Thank you very much for your answer, I saw in the documentation the relevant configuration option. Very very cool!

**Comment by erseco** [comment]
I'm trying to restory a really big ucompressed backup and I'm having memory issues
```
Restoring: ./2018-12-01-235555.dump
Restore tempfile created: 6.0 GiB
Are you sure you want to continue? [Y/n] y
Killed
```
Any idea of how to achieve the restoration?

**Comment by ZuluPro** [comment]
Hello @erseco 

I think in settings you can set the maximum size of SpooledTemporaryFile.

Dbbackup tries to keep file in RAM and not use filesystem.
The setting I'm talking will limit the used RAM amount and force DBbackup to use filesystem,
And so avoids to fill RAM and be killed.

**Comment by ZuluPro** [comment]
`1024**5` is really a lot, I don't know if a machine exist with this RAM amount :D

**Comment by pkkid** [comment]
I believe you want these numbers to be smaller, not bigger if you want to use less ram.

**Comment by erseco** [comment]
Sorry, I thought that the value was for file size, now it works like a charm!

**Comment by pkkid** [comment]
I understand, it is a rather terrible name for that setting.
