### ISSUE TITLE
The DBBACKUP_POSTGRESQL_BACKUP_COMMANDS setting is not an array

### ISSUE THREAD

**Issue by GeoffThorpeFT** [django-dbbackup/django-dbbackup#162]
The code assumes the DBBACKUP_POSTGRESQL_BACKUP_COMMANDS setting contains an array of commands (the result of a shlex).  This array is then later used in the system call to run the backup command (since that command expects an array of arguments).

I recommend running shlex against the contents of the setting. 
class PostgreSQLSettings(BaseEngineSettings):
    """Settings for the PostgreSQL database engine"""

    def get_extension(self):
        return getattr(settings, 'DBBACKUP_POSTGRESQL_EXTENSION', 'psql')

    def get_backup_commands(self):
        **backup_string** = settings.POSTGRESQL_BACKUP_COMMANDS
        **backup_commands = shlex.split(backup_string)**
        if not backup_commands:

**Comment by ZuluPro** [comment]
Not yet relevant with PR #165
