### ISSUE TITLE
DBBackup 3

### ISSUE THREAD

**Issue by ZuluPro** [django-dbbackup/django-dbbackup#166]
@benjaoming @mjs7231 

I think with recent modifications, DBBackup should became in version 3.
There are majors API change we've made and some I expect before release:

- [x] - DBCommands system has been refactored in easier system (#165) 
- [x] - Storage should be removed from DBBackup in favor of Django-Storage or else
- [x] - mediarestore is a must (#178)
- [x] - Backup between v2 and v3 must be possible
- [x] - Release note
- [ ] - User should be able to restore from DB from stdin (`-` option)

We should create a v3 branch for begin to work together.

What do you think about ?

**Comment by benjaoming** [comment]
@ZuluPro I have to say first of all that for my own goals and gains, dbbackup is already sufficient.

But for the philosophy moving forwards, I think it's still important to maintain a "semantic" versioning that indicates what's desirable for everyone: Namely that no external APIs change (i.e. the command line)?

Do you envision a version 3 with backwards incompatible changes to the command line?

Other than that, I really agree with the above, and for #165, I think the Release notes (changelog) will already be introduced? Btw. if you haven't seen it: http://keepachangelog.com/

**Comment by benjaoming** [comment]
Also, as usual: Great work!

The idea of avoiding a version 3 is by the way not to block things, but rather to avoid:

1) A separate branch
2) The risk of spending time on a bunch of support issues regarding backwards incompatible changes
3) Having to document and communicate backwards incompatible changes in other regards
4) People's backups shouldn't break, good to reduce the chances of that happening in case they forgot to pin the version of dbbackup...

**Comment by ZuluPro** [comment]
@benjaoming 

> 1) A separate branch

The new branch is for prepare the new release, after it has been merged to master and version bumped to 3, we won't support previous versions.

> 2) The risk of spending time on a bunch of support issues regarding backwards incompatible changes
I don't think it will be incompatible changes, major part will be refactoring of dbcommand.

> 3) Having to document and communicate backwards incompatible changes in other regards
Sure, a guide for porting from 2 to 3 is mandatory. I think basic configuration without many used settings can be ported easily. But I plan to remove deprecated storage.

> 4) People's backups shouldn't break, good to reduce the chances of that happening in case they forgot to pin the version of dbbackup...
I don't know really how to deal with it, I often forget to pin version of many things but it's an error from myself.

Otherwise I have an another ideas, maybe in future Integrate signals: pre_dump, post_dump, pre_restore, post_restore

**Comment by benjaoming** [comment]
Hi @ZuluPro :)

> I don't think it will be incompatible changes, major part will be refactoring of dbcommand.

If we don't have incompatible changes, I think it's enough to stick with the 2.x series. If we do, we *should* change the major digit.

My main reasoning is to keep with the [semantic versioning](http://semver.org/) idea. You can create wonderful new features and revolutionize the codebase completely without bumping the major digit, but when you *do* bump the very first digit in the version, you signal to users that they need to do something, i.e. that the upgrade is not possible without manual reconfiguration / refactoring.

> The new branch is for prepare the new release, after it has been merged to master and version bumped to 3, we won't support previous versions.

This wasn't to discourage creating a new branch, please if you feel it should be in a new branch, do so :) It's *just in case* someone else is contributing something, they could be confused about which codebase to merge against.. so the main thing is probably just to avoid that there's a big separate future release branch that sits around for a long time without being merged/rebased against the master branch.

> Sure, a guide for porting from 2 to 3 is mandatory.

Not sure then... if a port is necessary are your proposed changes "backwards compatible" or not?

I think the best way is the Django way.. to deprecate things in a release or two, then remove them entirely. That's how Django kept in the 1.x series for such a long time :)

**Comment by ZuluPro** [comment]
@benjaoming 
I'm agree with the idea of semantic versioning, but not the same for Django deprecation workflow.
Django is big project with many active developers, we can't wait for new version for deprecate and another new one for delete code. We code when we got time only...

Sorry I am maybe unclear about changement compatibility,
Connector system will force users with complex configuration to make some change.
As there is this major change, I think it's the good time for make a big clean of code.
As you said a new major version will warn users and shows that project continue to live.

**Comment by benjaoming** [comment]
Thanks for taking time to explain, @ZuluPro :) I'm in no way stubborn on principles about bumping the major version, and I sense it's a good decision because 1) you think so and because 2) I'm sure it will allow a more open minded approach to merging in new features and making the project progress.

I think we should keep merging everything into `master`, but if nothing is on the table for the current 2.x series, let's branch that series into its own stable `releases/2.x` branch.

**Comment by ZuluPro** [comment]
Hello @MiiRaGe,
Could I ask you to tests if you can backup/restore a MongoDB with master version
And if you can restore a backup from DBBackup V2 

Thank you

**Comment by ZuluPro** [comment]
@benjaoming @mjs7231 
I think it is done ...
Except stdin option and mongo that I'm unsure, it is great.

Can you make a review?

**Comment by MiiRaGe** [comment]
@ZuluPro I should have some free time next week to have a look.

**Comment by ZuluPro** [comment]
@MiiRaGe : DBBackup v3 is here !
Feel free to open an new issue if you have one.
