### ISSUE TITLE
dbrestore and GEOMETRY field

### ISSUE THREAD

**Issue by dorianamouroux** [django-dbbackup/django-dbbackup#168]
Hey guys,

I'm using dbbackup to save my data, but when I try to restore, I encounter this error : 
`ERROR 1416 (22003) at line 950: Cannot get geometry object from data you send to the GEOMETRY field`
I'm using this model fields : `from django.contrib.gis.geos import Point`

**Comment by ZuluPro** [comment]
Hello @dorianamouroux,
Thank for this issue. Can you give us more informations:
- What is your database engine (`django.contrib.gis.db.backends.mysq`) ?
- Can you give a traceback ?
- Do you make the restore on the same environment than source ?

We are making a refactoring for next version, could you try with DBbackup from master branch ?

**Comment by dorianamouroux** [comment]
Hi @ZuluPro !

I changed my database to mariaDB, that actually solves a lot of problems with all my migration. To answer to your questions : 
- My database engine is indeed `django.contrib.gis.db.backends.mysql`
- There were no traceback, as far as I can remember
- It was on the same computer when I dump and restore. 

When will the next version be finished ?

**Comment by ZuluPro** [comment]
Hello @dorianamouroux 
I thank you very much for your answer.

A last question, did you restore MySQL backup in MariaDB ?
As MySQL is the default MySQL engine, I must dig to know what happened.

Next version will be released in next 2 weeks (I hope).

**Comment by dorianamouroux** [comment]
When I got the bug, it was from MySQL to MySQL. Now the backup from MySQL and restore to MariaDB works perfectly

**Comment by ZuluPro** [comment]
@dorianamouroux DBBackup v3 isn't yet here, but I invite you to test our DBconnector system in master branch.
