### ISSUE TITLE
Integration with Django-cron

### ISSUE THREAD

**Issue by dorianamouroux** [django-dbbackup/django-dbbackup#169]
Hey guys,

I wanted to share how I integrated Django-dbbackup with Django-cron (http://django-cron.readthedocs.io/en/latest/) : 

```python
class Backup(CronJobBase):
    RUN_AT_TIMES = ['6:00', '18:00']
    schedule = Schedule(run_at_times=RUN_AT_TIMES)
    code = 'my_app.Backup'

    def __init__(self):
        directory = settings.DBBACKUP_STORAGE_OPTIONS['location']
        if not os.path.exists(directory):
            os.makedirs(directory)

    def do(self):
        management.call_command('dbbackup')
        management.call_command('mediabackup')
```
On the __init__ command, I create the folder for the backup if it doesn't exist.
I run my task twice a day, 6am and 6pm.
You can easily monitor if your backup went wrong from the admin panel.

Cheers !

**Comment by ZuluPro** [comment]
Hello @dorianamouroux 
Thank you very much for this contribution !
I included that here: https://github.com/ZuluPro/django-dbbackup/commit/da2dc8d070a99aaf407458f730dcd0d46c97a903
