### ISSUE TITLE
DBBACKUP_STORAGE_OPTIONS possible credential leak through debugging

### ISSUE THREAD

**Issue by ManuelGysin** [django-dbbackup/django-dbbackup#170]
Hello

Django protects in the debug mode some variables which are containing KEY, SECRET, PASSWORD and so on.

Because of the reason DBBACKUP_STORAGE_OPTIONS  is using lower case, django does not protect these variables.

![image](https://cloud.githubusercontent.com/assets/2873373/16244094/aee30e5e-37fa-11e6-81ad-10433a047a2d.png)

I suggest to change DBBACKUP_STORAGE_OPTIONS to upper case for protecting these sensitive credentials.

Thanks and greets
Manuel

**Comment by ZuluPro** [comment]
Hello @ManuelGysin,
Sorry for my latency, Yep great suggestion. I'll implement it soon.
It will be in next version.

**Comment by ManuelGysin** [comment]
This is fixed with https://github.com/django-dbbackup/django-dbbackup/blob/2dee62a5bcd8560cbdf6945bd29d762012c9d8ee/dbbackup/storage.py#L65
