### ISSUE TITLE
issue creating the pg_dump command for postgresql

### ISSUE THREAD

**Issue by amolinaalvarez** [django-dbbackup/django-dbbackup#172]
I'm gettng the following error try to create the backup for postgresql DB:

Error running:  pg_dump xxxxx --user=yyyyy --password=zzzz --clean 
b'/usr/lib/postgresql/9.3/bin/pg_dump: option \'--password\' doesn\'t allow an argument\nTry "pg_dump --help" for more information.\n'

pg_dumpd does not have the option --pasword=zzzz

Thanks in advance!

P.D. psql (PostgreSQL) 9.3.10

**Comment by ZuluPro** [comment]
Hello @amolinaalvarez 
Thank for this issue.

What is your DBBackup version ?

**Comment by amolinaalvarez** [comment]
Hi @ZuluPro,

Thanks a lot for you answer, I'm working on master because I need to work with Mongodb.

**Comment by ZuluPro** [comment]
@amolinaalvarez Sorry for my latency,
I'll make all that quite fast, I fix it soon.

**Comment by ZuluPro** [comment]
Hello @amolinaalvarez,
It should be fixed with #181 

Now, your password setting is set as environmental variable PGPASSWORD.
This is a security issue in production, so I suggest you to set a .pgpass file.

I let the issue opened, do not hesitate to say me if troubles stay.

**Comment by ZuluPro** [comment]
@amolinaalvarez : No news ?

**Comment by ZuluPro** [comment]
@amolinaalvarez : I think this issue is now resolved.
