### ISSUE TITLE
django mongodb engine doesn't supports django 1.8

### ISSUE THREAD

**Issue by amolinaalvarez** [django-dbbackup/django-dbbackup#173]
Hi again!

I'm using django 1.8 and after reviewing your code the only way to generate a backup using mongodb is using django mongodb engine, but it does not supports django1.8. In my case, I'm using mongoengine.
is there any option to use django-dbbackup and mongoengine?

Thanks in advance

**Comment by ZuluPro** [comment]
Hello @amolinaalvarez 
In master version (future 3.0), you can (potentialy) backup any database connected with Django or not.
So the mapping between DBEngine & DBConnector is simply a shortcut if you don't want to specify it yourself.

Does it answer to your question ?

**Comment by amolinaalvarez** [comment]
Hi @ZuluPro,

Thanks for you answers! Right now DBBackup works with the "DATABASES" that you configure on your settings.py, in my case, I have configured my database without using this settings's var, How could I generate my backup using DBBackup  in this situation?

Apart from the above drawback, I added my database in the settings.py (The only goal of this was to use DBBackup).

`DATABASES = {
    'mongodb': {
        'USER': '',
        'PASSWORD': '',
        'NAME': 'xxxxx',
        'HOST': 'localhost',
        'PORT': '27017',
    }
}`

As you can see, I did not define the ENGINE option, because of django mongodb engine does not supports django1.8. So I modified your source code in order to use this case:

`CONNECTOR_MAPPING = {
    'django.db.backends.sqlite3': 'dbbackup.db.sqlite.SqliteConnector',
    'django.db.backends.mysql': 'dbbackup.db.mysql.MysqlDumpConnector',
    'django.db.backends.postgresql': 'dbbackup.db.postgresql.PgDumpConnector',
    'django.db.backends.postgresql_psycopg2': 'dbbackup.db.postgresql.PgDumpConnector',
    'django.db.backends.oracle': None,
    'django_mongodb_engine': 'dbbackup.db.mongodb.MongoDumpConnector',
    'django.contrib.gis.db.backends.postgis': 'dbbackup.db.postgresql.PgDumpGisConnector',
    'django.contrib.gis.db.backends.mysql': 'dbbackup.db.mysql.MysqlDumpConnector',
    'django.contrib.gis.db.backends.oracle': None,
    'django.contrib.gis.db.backends.spatialite': 'dbbackup.db.sqlite.SqliteConnector',
    None: 'dbbackup.db.mongodb.MongoDumpConnector',
}
`
Adding the last line, everything seems to work fine, is that the best way to resolve my problem?

Thanks!

**Comment by ZuluPro** [comment]
Hello @amolinaalvarez,
Really sorry for my latency...

I don't think it will be the best way:
If another DB engine don't use ``ENGINE`` options, it won't be OK.
But with ``CONNECTORS`` setting, you could be able to make the job.

**Comment by ZuluPro** [comment]
@amolinaalvarez 
Is this issue still relevant ?

**Comment by amolinaalvarez** [comment]
Hi @ZuluPro,

I apologise for the delay. I did not have the chance to work on this, but during the next days I hope to work on it again. I'm going to try your suggestion and I'll sent you my feedback.

Thanks a lot.

**Comment by ZuluPro** [comment]
@amolinaalvarez : Any news ?

**Comment by jonathan-s** [comment]
Closing this, if it is still an issue feel free to comment / re-open.
