### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pg_dump'

### ISSUE THREAD

**Issue by flyalex** [django-dbbackup/django-dbbackup#179]
Hi,
My project is up on Python3.5, Django 1.9 and PostgreSQL.

With basic settings I do python manage.py dbbackup and get FileNotFoundError: [Errno 2] No such file or directory: 'pg_dump'.

Should it actually work on my configuration?

Thanks!

**Comment by ZuluPro** [comment]
Hello @flyalex,
Thank for this issue.

Which version of DBBackup do you use ? master ?
Do you have an error traceback ?
Do you have ``pg_dump`` installed on your system (``which pg_dump``)

**Comment by flyalex** [comment]
@ZuluPro, thank you!
This helped: PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
My fault. Will continue configure django-dbbackup.
