### ISSUE TITLE
Database name in media backup breaks path if using sqlite

### ISSUE THREAD

**Issue by mjs7231** [django-dbbackup/django-dbbackup#18]
backup_media uses settings.DATABASES['default']['NAME'] to build its filename. When using sqlite the DB name might already be a path. (e.g. path/to/my/db/db.sqlite3) Therefore the output path will be corrupted. This causes filesyste_storeage to backup to wrong path and ftp storage to not find the file at all.

Solutions: 1. Don't use db name for media backups. Got nothing to do with DB anyway.
Fix the 2DO in line 56 of backup_media.py so database name can be excluded via DBBACKUP_FILENAME_TEMPLATE

**Comment by ZuluPro** [comment]
I think do not use DB's name is good beginning. In unittest DB's name could be ``':memory:'`` for example.
DBBACKUP_FILENAME_TEMPLATE has been improved implemented with PR #97
