### ISSUE TITLE
Bug: "Exception Value: SpooledTemporaryFile instance has no attribute __len__"

### ISSUE THREAD

**Issue by mjs7231** [django-dbbackup/django-dbbackup#19]
I failed to run dbbackup, this exception keeps getting raised. It seems you are using SpooledTemporaryFile "file like objects" and pass them directly to dropbox client "put_file" method as "body" parameter, and it only supports file_like objects with "getvalue" method (like StringIO).
i'm attaching my "requirements.txt", the exception traceback, and my solution, which is to use cStringIO for the chunks.
if it makes any difference, this happens on my development setup, using sqlite. perhaps dropbox released a new package into pip that broke compatibility?
Thank you for this very useful module, Shlomi.

NOTE: Downgrading to dropbox==1.6.0 fixed the issue for me. It might be worth pinning requirements in setup.py, Michael.

**Comment by ZuluPro** [comment]
The version of dropbox stored in PyPi is now outdated. It doesn't support Python3. A new version has been made by Dropbox here: https://github.com/dropbox/dropbox-sdk-python
It is supposed to be fully compatible with older versions and Python.

I've made a PR at django-storage-redux here: https://github.com/jschneier/django-storages/pull/76
If it is merged, I think we'll drop dropbox code from dbbabckup and use Redux's one.

**Comment by ZuluPro** [comment]
I think this issue may be closed with this PR #117
