### ISSUE TITLE
pg_dump binary mode

### ISSUE THREAD

**Issue by ZuluPro** [django-dbbackup/django-dbbackup#190]
As mentioned in issue #143 make usage of compression with Postgres should be a great thing.

This kind of compression needs Postgres binary mode, so usage of `pg_restore`, we need to write a `PgDumpBinaryConnector`

Otherwise binary mode offers many benefits in file size.

**Comment by jonathan-s** [comment]
A PgDumpBinaryConnector now exists so this can be closed.
