### ISSUE TITLE
Django 1.10 support release ?

### ISSUE THREAD

**Issue by noirbizarre** [django-dbbackup/django-dbbackup#196]
Hi !

Thanks for this project !

Is there any release planned soon to enable support for Django 1.10 ? (Not necessarily the 3.0 release, just a release including 56f4e912cd9a which prevent to use Django 1.10)

**Comment by ZuluPro** [comment]
Hello @noirbizarre 
I didn't plan it, but could be made, you point me the right commit so...

I think 3.0 will be here very soon,
Just need some check.

Can't you wait for it ?

**Comment by noirbizarre** [comment]
Hi @ZuluPro !

Thanks for responding so fast :+1: 

Yes I can wait if release 3.0 is coming, it's fine to me !

**Comment by ZuluPro** [comment]
Hello @noirbizarre ,
DBBackup v3.0.0 is here !

**Comment by noirbizarre** [comment]
Thanks @ZuluPro !!!
I'm going to instal and test it right now !!
