### ISSUE TITLE
Support for dbbackup of database in Docker container

### ISSUE THREAD

**Issue by bhanduroshan** [django-dbbackup/django-dbbackup#197]

**Comment by ZuluPro** [comment]
@bhandariroshan 
I often think about the following thing:
To have a standalone Django project allowing to backup (or restore) without change my `settings.py`

I don't think it is really in DBBackup's domain, but more a way to design your architecture.
If you have a great Docker image for DBBackup, do not hesitate to submit us, we'll add it to the organisation and the [integration documentation](http://django-dbbackup.readthedocs.io/en/latest/integration.html)

**Comment by dorianamouroux** [comment]
This one is up to you, I did it myself.
You can use the file system storage and mount your backup folder into your container.
docker-compose run --rm web python manage.py [backup command here]

**Comment by ZuluPro** [comment]
Could you give us an URL?

**Comment by dorianamouroux** [comment]
I think I used this one when I was getting started with Docker and Docker-compose
https://docs.docker.com/compose/django/

**Comment by ZuluPro** [comment]
OK, let me explain exactly that I have in head:
1) I think developers will create their own Docker image of their apps
2) We must provides them a Docker image acting like ``manage.py``, with project settings or specific to the backup action
3) The DBBackup image could contain a wrapper to easily dump/restore database/media

I don't think docker-compose will be helpful: We need to launch a thread for our action and let it die. No daemon here. We should create a single container linked to the database one(s).

Maybe you don't see this like that at all ?

**Comment by ZuluPro** [comment]
> We I run docker-compose run web --rm python manage.py dbbackup I will have the backup in my local folder.
This is what I wanted to know ...

> I think it doesn't make sense to have a docker image just for the backups, if you are using docker with your project, you should be able to access to manage.py

While I develop this app, I always think about huge companies with separated team, They could have a backup team which mustn't (or can't) have access to the project code. Instead they could have a separated light project with other configuration and specific tools, for example: Have different database credentials, dump/restore specific tools or else. 
Developers may don't want admin to have every `manage.py` actions.
So it makes sense to have a container for backup only

**Comment by bhandariroshan** [comment]
Thanks everyone, I did my own implementation. Here's what I did:

a.  Created a pgdump inside the container

```
backup_command_name = sudo docker exec -i <container_name> + bash -c  'pg_dump -U <db_user>  <db_password> > <file_name> '
os.system(backup_command_name)

```

b. Moved it outside the container to local file system using docker cp 
```
 copy_command_name = docker cp <container_name>:<file_name> <path_to_local_folder>
os.system(copy_command_name)
```

c.  Finally used dropbox ibrary to sync it to my dropbox.

**Comment by ZuluPro** [comment]
@bhandariroshan : Thank you for this example.
I'm looking something more "Djangonic", using entirely DBBackup mechanism.

**Comment by bhandariroshan** [comment]
@ZuluPro look forward to it .. it would be awesome..

**Comment by busla** [comment]
I don´t see how this is possible unless `pg_dump` is available in the application image.

**Comment by ZuluPro** [comment]
@busla I think the best way is the following:
- We create a base image for Django-DBBackup
- Maybe create sub images (MySQL, Postgres, etc) from base
- Users use one these images with its settings file or env vars

What do you think about ?

**Comment by busla** [comment]
I think the problem at hand is not related to `django-dbbackup` at all. When isolating services into images (app, db, nginx, redis, et.c) and keeping the images as lean as possible (separation of concerns) the compromise is the range of tools we normally have access to.

If `django-dbbackup` will use `pg_dump` the tool needs to be available in the image, like you suggest, as a merged child image.

Everyone has their preference on how their application images is built so I think offering a `django-dbbackup` image might not get any attention. But who knows.

Perhaps we could look at it from the database side. Extend the DB images (postgres, mysql, etc) and link to the application container from there. Somehow relay commands from the application container to the database container?

**Comment by ZuluPro** [comment]
I don't think we should use database images. They are here for server, not client.
In the case of AWS RDS this image doesn't exist.

I think about a real standalone image with nothing more than the requirements to connect to database and dbbackup. No need to inherit from user's project, just need an appropriate settings.py.

**Comment by noxxer** [comment]
And such a beautiful solution almost turned out...

```
pg_dump: server version: 11.4; pg_dump version: 9.6.8

pg_dump: aborting because of server version mismatch
```
until I realized that both locally and in production I can't make it work using Docker.

any ideas?

it seems that you can share a single pg_dump file inside the container with the application, but I'm not sure that this is enough

**Comment by poiedk** [comment]
Finally got it work!!!!

Here's my Dockerfile

`FROM python:3.8.2-alpine3.11
RUN apk add --no-cache \
    postgresql-client \
    postgresql-dev \
    pkgconfig \
    git \
    gcc \
    openldap \
    libcurl \
    python3-dev \
    gpgme-dev \
    libc-dev

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/app/`

**Comment by jonathan-s** [comment]
@bhanduroshan, It looks like you've resolved your issue. It's unclear if there is anything that we should be doing / add to this project to make things easier. If you feel like something concrete can / should be done we can re-open this issue.

**Comment by Tankovod** [comment]
> Finally got it work!!!!
> 
> Here's my Dockerfile
> 
> ```
> FROM python:3.8.2-alpine3.11
> RUN apk add --no-cache \
>     postgresql-client \
>     postgresql-dev \
>     pkgconfig \
>     git \
>     gcc \
>     libcurl \
>     python3-dev \
>     gpgme-dev \
>     libc-dev
> 
> # set work directory
> WORKDIR /usr/src/app
> 
> # set environment variables
> ENV PYTHONDONTWRITEBYTECODE 1
> ENV PYTHONUNBUFFERED 1
> 
> # install dependencies
> RUN pip install --upgrade pip
> COPY ./requirements.txt /usr/src/app/requirements.txt
> RUN pip install -r requirements.txt
> 
> # copy project
> COPY . /usr/src/app/
> ```



> Finally got it work!!!!
> 
> Here's my Dockerfile
> 
> ```
> FROM python:3.8.2-alpine3.11
> RUN apk add --no-cache \
>     postgresql-client \
>     postgresql-dev \
>     pkgconfig \
>     git \
>     gcc \
>     libcurl \
>     python3-dev \
>     gpgme-dev \
>     libc-dev
> 
> # set work directory
> WORKDIR /usr/src/app
> 
> # set environment variables
> ENV PYTHONDONTWRITEBYTECODE 1
> ENV PYTHONUNBUFFERED 1
> 
> # install dependencies
> RUN pip install --upgrade pip
> COPY ./requirements.txt /usr/src/app/requirements.txt
> RUN pip install -r requirements.txt
> 
> # copy project
> COPY . /usr/src/app/
> ```

Great work, BRO !
