### ISSUE TITLE
Logger stopped working in version 3.0.x

### ISSUE THREAD

**Issue by psychok7** [django-dbbackup/django-dbbackup#203]
@ZuluPro I have been testing out version `3.0.0` and `3.0.1` and i noticed my code's custom loggers stopped working.
```
log = logging.getLogger('logit')
log.info('Something')
 ```

This code does not print anything, but when i downgrade to version `2.5.0` or less it works fine. This is affecting all my custom loggers in my code(tested with manage commands), only `print()` or `stdout.write` work.

Any ideas?
Cheers

**Comment by psychok7** [comment]
PS: i am using `Django 1.10`

**Comment by ZuluPro** [comment]
It's been a long time I want to make DBBackup logging clearer.
Let me some time to look at it deeper.

**Comment by math609** [comment]
I can confirm the issue is still present with 3.0.1 release. Also it affects Django 1.9.9 and affects ANY logger defined in the LOGGING dict in settings.py file

**Comment by ZuluPro** [comment]
@math609 @psychok7:
V3.0.2 released !!
