### ISSUE TITLE
Wrong DBBACKUP_CLEANUP_KEEP on multiple dbs

### ISSUE THREAD

**Issue by adi-** [django-dbbackup/django-dbbackup#206]
When one DB is used, everything works fine. However, when you have 2 DBs `DBBACKUP_CLEANUP_KEEP` is used for those 2 DBs combined! In the end I have (when using defaults) only 5 backup files for each DB.

**Comment by ZuluPro** [comment]
Hello @adi- Thanks for reporting this issue.
If I understand well, you set `DBBACKUP_CLEANUP_KEEP` to `10`,
And want to keep 10 for each database ?

**Comment by adi-** [comment]
Yes. For me it is a reasonable functionality.

**Comment by ZuluPro** [comment]
@adi- Ok, effectively DBBackup has not yet been implemented for that.
But just let me some time and you'll have it in v3.0.3.

**Comment by adi-** [comment]
Great! Thanx!

**Comment by adi-** [comment]
@ZuluPro v3.0.3 milestone is completed. Could you push it to pipy?

**Comment by ZuluPro** [comment]
Oops sorry, I forgot to publish :D
