### ISSUE TITLE
dbrestore --servername SERVERNAME doesn't work

### ISSUE THREAD

**Issue by adi-** [django-dbbackup/django-dbbackup#207]
Despite the use of `--servername` dbrestore downloads the most recent file of any server.

Also, check out issue #208

**Comment by ZuluPro** [comment]
@adi- Sorry for my latency
I took time to look at it deeper:
``--servername`` and its setting ``SERVERNAME`` are here just for customize filenames. During the heavy v3 refactoring I saw that and have two choices:
- Remove this part of code and risk to break users' configuration
- Keep them and implement filtering and more

As you can see, option 2 was chosen. As you seem to need it, it will made faster.
