### ISSUE TITLE
Add SFTP Support

### ISSUE THREAD

**Issue by mjs7231** [django-dbbackup/django-dbbackup#21]
Im just wondering, why you don't provide an SFTP storage class? Is there some reasons or was it not needed by anybody yet? Alternatively i could take a look at it and create a pull request, if this feature is wanted.

**Comment by ZuluPro** [comment]
I think this issue can be closed: https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/storage/sftp_storage.py ?

**Comment by benjaoming** [comment]
Yes, the feature has been added :+1:  Any subsequent wishes or problems with the sftp storage should be reported elsewhere :)
