### ISSUE TITLE
dbrestore with PostgreSQL doesn't recognize errors during restore

### ISSUE THREAD

**Issue by patrickhallen** [django-dbbackup/django-dbbackup#211]
Hi,

dbrestore with PostgreSQL doesn't recognize errors during restore, meaning it quits without any error message when the underlying psql encounters any error while potentially doing nothing. The reason for this is  that psql terminates with an exit value of 0 if it encounters any SQL errors unless ON_ERROR_STOP=on is set.

One possible fix is to add  '--set ON_ERROR_STOP=on' to the psql command. The pull request #212 implements this proposed fix.

**Comment by ZuluPro** [comment]
Thank you very much for this issue.
