### ISSUE TITLE
Example settings in documentation are wrong

### ISSUE THREAD

**Issue by publysher** [django-dbbackup/django-dbbackup#216]
The latest documentation still suggests the following settings:

```python
INSTALLED_APPS = (
    ...
    'dbbackup',  # django-dbbackup
)

DBBACKUP_STORAGE = 'dbbackup.storage.filesystem_storage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/var/backups'}
```

This fails with an error `module 'dbbackup.storage' has no attribute 'filesystem_storage'`

If I'm understanding this correctly, the correct example should have

```python
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
```

**Comment by publysher** [comment]
Please note that this is only on the `installation` page: 

http://django-dbbackup.readthedocs.io/en/latest/installation.html

**Comment by ZuluPro** [comment]
Hello @publysher 
Thank you very much for this issue,
I will fix it tonight.

But for now, if you want to use the filesystem storage,
Use the Django one: 

```
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/my/backup/dir/'}
```

**Comment by ZuluPro** [comment]
@publysher Master's version is now updated.
Latest will be at next release.

Thank for the issue and sorry for the problem ? :D

**Comment by PetrDlouhy** [comment]
@ZuluPro This is still present in current documentation for stable confusing new users.

**Comment by mmmcorpsvit** [comment]
i was confused))), please fix
P.S. How i can set full path to pg_dump ?
