### ISSUE TITLE
Wrong date in generated file names

### ISSUE THREAD

**Issue by adi-** [django-dbbackup/django-dbbackup#218]
![screenshot](https://cloud.githubusercontent.com/assets/340741/18865525/03d6d330-849c-11e6-92ea-146c9ac849bf.png)

Backup is scheduled at 00:00 each day. Check out the file date modification date – it is ok, but the date in file name is wrong. It is probably GMT time, not a local time, right? My current local time is CEST (+2h), so it explains everything.

I am on v3.0.3

**Comment by adi-** [comment]
More data:

```
:~$ timedatectl
      Local time: Tue 2016-09-27 10:26:50 CEST
  Universal time: Tue 2016-09-27 08:26:50 UTC
        RTC time: n/a
       Time zone: Europe/Warsaw (CEST, +0200)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

**Comment by ZuluPro** [comment]
To create the date part, we used: `timezone.now().strftime(settings.DATE_FORMAT)`

Do you set `USE_TZ` at `True` or `False` ?

**Comment by adi-** [comment]
It is set to `True`

**Comment by ZuluPro** [comment]
And what is your `TIME_ZONE` setting of django ?

**Comment by adi-** [comment]
`TIME_ZONE = 'Europe/Warsaw'`

**Comment by adi-** [comment]
Hi, anything with this?

**Comment by adi-** [comment]
As mentioned in #219, this issue is fixed and can be closed.
