### ISSUE TITLE
Dbbackup overwrites all but the latest file

### ISSUE THREAD

**Issue by mjs7231** [django-dbbackup/django-dbbackup#22]
As far as I can see, dbbackup always creates single backup called [databasename].backup and overwrites previous backups, since they're already called the same name.

It looks like the issue might be in save_new_backup() in dbbackup.py. Could this instead use similar logic to get_backup_basename() in mediabackup.py, which adds a timestamp?

**Comment by mallyvai** [comment]
Wanted to chime in that this is still an issue and related to https://github.com/mjs7231/django-dbbackup/issues/52 .

The comments / doc mentioned that big chunks of the codebase were going to be refactored / rewritten. Is this still the case? If the codebase is going to be relatively static off whatever is in prod, I'd love to contribute some patches more aggressively.

**Comment by benjaoming** [comment]
I don't think there's gonna be refactors, no actions except for some old comments indicate this.

**Comment by ZuluPro** [comment]
I think this issue is no more relevant with current version. File's name has been refactored.
