### ISSUE TITLE
--quiet doesn't actually suppress logging output

### ISSUE THREAD

**Issue by dwdyer** [django-dbbackup/django-dbbackup#226]
This has been an issue for a while (since I moved from version 1.9 to 2.x I think) and still is with 3.0.4. If you specify `--quiet`, you still get three lines of output:

`Writing file to default-myproject-2016-11-19-010002.dump.gz`
`Writing file default-myproject-2016-11-19-010002.dump.gz`
`Writing file default-myproject-2016-11-19-010002.dump.gz`

This has been a minor annoyance because it causes me to get an email every time my cron job runs. Previously I'd only get emailed if there was an error.

I took a look at the code and it seems like it should be dealt with by `_set_logger_level` in this file: https://github.com/django-dbbackup/django-dbbackup/blob/2dee62a5bcd8560cbdf6945bd29d762012c9d8ee/dbbackup/management/commands/_base.py but I can't see where that actually gets called.

**Comment by ZuluPro** [comment]
Hello @dwdyer 
Thanks I will fix logger soon.

you could configure `'dbbackup.command'` logger in your `LOGGING` setting, does it help you ?

**Comment by dwdyer** [comment]
Thanks. It's not a major problem, I just thought I'd mention it while I remembered.

I just tried setting the level for 'dbbackup.command' to 'ERROR' in my LOGGING setting. It doesn't seem to make a difference but I'm not sure why. Perhaps I've done something wrong somewhere.

**Comment by ZuluPro** [comment]
Hello @dwdyer 
This should be fixed with last version 3.1.0
