### ISSUE TITLE
pg_restore is not compatible with `--set ON_ERROR_STOP=on`

### ISSUE THREAD

**Issue by vvarp** [django-dbbackup/django-dbbackup#232]
Since `--set ON_ERROR_STOP=on` is being automatically added when restoring postgresql backups, it is no longer possible to use `pg_restore` instead of default `psql`

I think this aspect should be configurable via settings, in a similar way as clean or single-transaction switches - but I am not sure what was the design decision behind that

**Comment by ZuluPro** [comment]
Hello @vvarp,
Sorry for my latency,

The solution for this is coming: https://github.com/ZuluPro/django-dbbackup/commits/pgrestore

I'll make a Connector dedicated to binary PostgreSQL.
I still have some trouble with tests but hope it will merged soon...

**Comment by ZuluPro** [comment]
@vvarp Could you test PR #241 resolve your problems ?

**Comment by vvarp** [comment]
@ZuluPro thanks, that looks solid - I'll give it a try asap and report my findings
