### ISSUE TITLE
Why not use `psycopg` for PostgreSQL database dump / restore?

### ISSUE THREAD

**Issue by MickaelBergem** [django-dbbackup/django-dbbackup#233]
`psycopg` (http://initd.org/psycopg/) is the most used Python driver for PostgreSQL databases, and is even **required by Django** when using Postgres as the database, so we can assume it is **always installed** when Django DBBackup commands are executed.

In my case (a Docker container based on `python:3.5-slim`) the PostgreSQL client is not available, although the `psycopg` driver is installed and totally working. The client is not available due to image inheritance (even changing the base image to the main `python:3.5` - or `3.6` doesn't change anything) as I am using Postgres v9.5 and the available client is only `postgres-client-9.4` on pre-xenial Ubuntu releases -> not compatible.

I thus cannot use DBBackup commands anymore (since I moved to Docker) :'(

Using `psycopg` instead of raw commands would solve this specific issue while providing an easier / faster / lighter installation process. Is there any reason `psycopg` is not used, apart from a lack of time on the dev side? Did someone ever tried this?

**Comment by MickaelBergem** [comment]
@ZuluPro sorry for the delay: I understand the official tools are robust and stable (when available), my point was just that it adds dependencies.

I finally changed my Dockerfile to add the Postgres apt repository and be able to install the `postgres-client-9.5`. It works like a charm but I depend on the other layers (external repository, etc.).

**Comment by ZuluPro** [comment]
Hello @MickaelBergem,

Could you give us a sample of your Docker image ?
It interesting for future.

**Comment by MickaelBergem** [comment]
Sure:

Assuming you already have `wget` installed, here are the steps to add in your Dockerfile:

```
# We need PostgreSQL 9.5
COPY postgresql.list /etc/apt/sources.list.d/
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-client-9.5 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

You also need the file `postgresql.list`:

```
deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main
```

This `wheezy` comes from the fact I am using the base image `python:3.5-slim` which relies on Debian Wheezy.
