### ISSUE TITLE
dbrestore of sqlite database does not like newlines

### ISSUE THREAD

**Issue by setphen** [django-dbbackup/django-dbbackup#238]
I get a UserWarning when running dbrestore for an sqlite database:

`UserWarning: Error in db restore: unrecognized token: `
And then a print of some text I have entered in a field. This only happens on Textfields that have line breaks. The rest of the db restore seems to work as expected.

Python 3.4

**Comment by davidfokkema** [comment]
+1

**Comment by jonathan-s** [comment]
Conversation moved to #254
