### ISSUE TITLE
Wrong default value for `settings.STORAGE`?

### ISSUE THREAD

**Issue by pacahon** [django-dbbackup/django-dbbackup#239]
Hello, `filesystem_storage` looks like legacy code?
```
STORAGE = getattr(settings, 'DBBACKUP_STORAGE', 'dbbackup.storage.filesystem_storage')
```

**Comment by ZuluPro** [comment]
Hello @pacahon : https://github.com/django-dbbackup/django-dbbackup/pull/237

**Comment by pacahon** [comment]
@ZuluPro Ok! Sorry, didn't mention it.
