### ISSUE TITLE
Changelog needed

### ISSUE THREAD

**Issue by adi-** [django-dbbackup/django-dbbackup#242]

**Comment by anx-ckreuzberger** [comment]
Seriously, a changelog (e.g., on read-the-docs) for each version would be really nice.

**Comment by ZuluPro** [comment]
@anx-ckreuzberger Feel free to propose a simple way to do it.

**Comment by anx-ckreuzberger** [comment]
Create a ``changelog.rst`` in your docs/ folder, and include it in your ``index.rst``.
For each "major" change, add a line which describes the change and link it to a github issue (if one is available) like this:

- Added django 1.10/1.11 support #243
