### ISSUE TITLE
Restore fails when using --encrypt

### ISSUE THREAD

**Issue by mjs7231** [django-dbbackup/django-dbbackup#25]
Remove the empty raise, then restore goes right.
Env:

    DEBUG = True
    DATABASE["default"]["ENGINE"]: "django.db.backends.sqlite3"

**Comment by ZuluPro** [comment]
Do you still have this bug, after the recents commits ?

**Comment by ZuluPro** [comment]
Re-Up!
Maybe this issue should be closed, we cover this part in unittests and there's no traceback ?
