### ISSUE TITLE
restore_dump and _restore_dump

### ISSUE THREAD

**Issue by rgaiacs** [django-dbbackup/django-dbbackup#256]
[dbbackup/db/base.py](https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/db/base.py) has

~~~
    def restore_dump(self, dump):
        """
        :param dump: Dump file
        :type dump: file
        """
        result = self._restore_dump(dump)
        return result

    def _restore_dump(self, dump):
        """
        Override this method to define dump creation.
        :param dump: Dump file
        :type dump: file
        """
        raise NotImplementedError("_restore_dump not implemented")
~~~

but [dbbackup/db/sqlite.py](https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/db/sqlite.py) override `restore_dump` instead of `_restore_dump`. Any reason why we have the two methods instead of just 

~~~
    def restore_dump(self, dump):
        """
        Override this method to define dump creation.
        :param dump: Dump file
        :type dump: file
        """
        raise NotImplementedError("restore_dump not implemented")
~~~

**Comment by ZuluPro** [comment]
Hello @rgaiacs 
Yes there are ±:
- I created both methods to let developer implement more easily their Connectors with subclass, mixins, etc...
- As SQLite is pure a Python Connector (no underlying tools), I didn't think about subclass it

Cheers
