### ISSUE TITLE
RemovedInDjango110Warning: OptionParser

### ISSUE THREAD

**Issue by pkkid** [django-dbbackup/django-dbbackup#263]
Just opening this as a heads up that dbbackup may stop working in Django 1.10 if we don't update this.

```
/home/mjs7231/.virtualenvs/pk/lib/python3.5/site-packages/django/core/management/base.py:265: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  RemovedInDjango110Warning)
```

**Comment by ZuluPro** [comment]
Hello @pkkid 
I made a piece of code about that: https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/management/commands/_base.py#L57

`optparse` is only used with Django < 1.11.

**Comment by pkkid** [comment]
Cool, sorry for the noise.
