### ISSUE TITLE
Getting error when trying to backup to Dropbox

### ISSUE THREAD

**Issue by wil831** [django-dbbackup/django-dbbackup#265]
django-dbbackup==3.1.3
django-storages==1.6.5
dropbox==8.2.0

> TypeError: expected request_binary as binary type, got <class 'django.core.files.base.File'>
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/dbbackup/utils.py", line 111, in wrapper
>     func(*args, **kwargs)
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/dbbackup/management/commands/dbbackup.py", line 61, in handle
>     self._save_new_backup(database)
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/dbbackup/management/commands/dbbackup.py", line 88, in _save_new_backup
>     self.write_to_storage(outputfile, filename)
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/dbbackup/management/commands/_base.py", line 88, in write_to_storage
>     self.storage.write_file(file, path)
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/dbbackup/storage.py", line 82, in write_file
>     self.storage.save(name=filename, content=filehandle)
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/django/core/files/storage.py", line 54, in save
>     return self._save(name, content)
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/storages/backends/dropbox.py", line 111, in _save
>     self.client.files_upload(content, self._full_path(name))
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/dropbox/base.py", line 1938, in files_upload
>     f,
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/dropbox/dropbox.py", line 234, in request
>     timeout=timeout)
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
>     timeout=timeout)
>   File "/home/bpmdb/.virtualenvs/bpmdb/lib/python3.5/site-packages/dropbox/dropbox.py", line 369, in request_json_string
>     type(request_binary))

**Comment by dwdyer** [comment]
This is a bug in django-storages. I got it working by using the latest HEAD version, so it's fixed, but they haven't included it in a release yet.

On a related note, I had to upgrade django-storages and dropbox because the Dropbox V1 API has been switched off. Since doing so, and with the HEAD version of django-storages, I get an error if I try to use `--clean` with django-dbbackup. I'm not sure which package is at fault.
