### ISSUE TITLE
NOTE: Required S3 permissions

### ISSUE THREAD

**Issue by racitup** [django-dbbackup/django-dbbackup#268]
In case there is someone else out there scratching their head about what exact IAM policy permissions are required on an AWS S3 bucket for this to work, they are below. This is using the boto3 storage backend. Replace `bucket-name` with your, erm, bucket name.
The `PutObjectAcl` had me scratching my head for a while...

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Files",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-name/*"
            ]
        },
        {
            "Sid": "Bucket",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-name"
            ]
        }
    ]
}
```

**Comment by ZuluPro** [comment]
Thank you very much for this issue,
But I think this kind of help should be addressed to Django-Storages or other storage project.

As we don't maintain storage we can't advise how to configure it.
But we should warn that the used storage must gives writes permissions (or not in case of read-only client)
