### ISSUE TITLE
Exclude-table-data issues

### ISSUE THREAD

**Issue by psychok7** [django-dbbackup/django-dbbackup#274]
@ZuluPro Hi there, while starting to use the `exclude` option with my Postgres installation (i have a few million rows on a specific table and i don't really need that data in dev mode) i noticed that you are using `--exclude-table` that will not dump the table and i am running into migration issues because of it. But in my case i need to keep the table structure so i figured using `--exclude-table-data` might be a better option. Would you be opened to a new PR adding this functionality or even replacing the exiting `--exclude-table` with `--exclude-table-data` ?

Cheers

**Comment by ZuluPro** [comment]
Yes you can propose this PR.
Thanks
