### ISSUE TITLE
doesn't work when using docker

### ISSUE THREAD

**Issue by amineparis** [django-dbbackup/django-dbbackup#277]
If `django` and` postgresql` use different docker containers (which is the recomanded case), `django-dbbackup` commands don't work since it can't communicate to another container

**Comment by amineparis** [comment]
@ZuluPro  So respectful, TY

**Comment by ZuluPro** [comment]
@amineparis 
As your Django project communicates with your database, command can too...
You can use your middleware container to run commands,
Or create another container for dbbackup.

But this issue/question isn't DBBackup related more about how you deal with your architecture.
