### ISSUE TITLE
example with call_command 

### ISSUE THREAD

**Issue by Vadorequest** [django-dbbackup/django-dbbackup#278]
I'm trying to write a script but I don't get how to provide the parameters...

`management.call_command("mediabackup", compress=True, clean=True)` doesn't seem to take arguments into account. And I don't understand how to use the `-o` and `-O` options since there is no `--` version.

`management.call_command("mediabackup", '--clean')` throw exception `TypeError('expected string or buffer',)`

Please add usage examples.

**Comment by ZuluPro** [comment]
Hello @vadorequest,
There are few examples in tests 

Feel free to make a documentation PR

**Comment by Vadorequest** [comment]
Thanks @ZuluPro, I had a look at the https://github.com/django-dbbackup/django-dbbackup/blob/master/tests/runtests.py#L59 test file, but I still don't quite get it. There is no example using `call_command` but `execute_from_command_line` instead.

To my understanding, using `clean=True` should delete other previous backups, but it does not in my example.

**Comment by ZuluPro** [comment]
Hey @Vadorequest 
Look at here:
https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/tests/functional/test_commands.py

**Comment by jonathan-s** [comment]
@Vadorequest, I'm closing this, feel free to ping me again if this isn't resolved.
