### ISSUE TITLE
Host parameter for AWS S3 Storage Options is not being respected

### ISSUE THREAD

**Issue by voiddragon** [django-dbbackup/django-dbbackup#284]
I've set the host parameter here but the request URL is still being directed to https://bucket-name.s3.amazonaws.com

```
DBBACKUP_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DBBACKUP_STORAGE_OPTIONS = {
    'access_key': "",
    'secret_key': "",
    'bucket_name': "bucket-name",
    'host': "s3-eu-west-1.amazonaws.com",
    'location': 'database-backups/'
}
```

**Comment by voiddragon** [comment]
![screen shot 2018-05-23 at 10 27 38 am](https://user-images.githubusercontent.com/1821882/40400313-2ee2ee70-5e74-11e8-9358-61284169214c.png)

@ZuluPro The documentation states that the host setting in the storage options can be used to change the default boto3 hostname, do I have to override the boto3 settings instead for this to work?

**Comment by ZuluPro** [comment]
@voiddragon The documentation primarly states that the storage is a third package and you should read its doc to understand it.

**Comment by voiddragon** [comment]
@ZuluPro Yes I managed to get it to work by modifying the settings for storages, I think the documentation should be updated to reflect that the host setting does not actually work and that it should be updated on the storages settings level to avoid future confusion.

**Comment by bartmika** [comment]
I've had this very same issue and fixed it before finding what other people wrote about it on github. I give a +1 for having this issue fixed by the developers.

**Comment by bittner** [comment]
I spent quite some time to figure out the solution. The only problem with the documentation, currently, is that the `'host'` option doesn't exist anymore with [django-storages](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L293-L324). Instead, we now need to use the `'endpoint_url'`, e.g.

```python
DBBACKUP_STORAGE_OPTIONS = {
    'endpoint_url': 'https://s3-compatible-service.example.com',
    'access_key': '*************',
    'secret_key': '*************',
    'bucket_name': 'my-backup',
    'default_acl': 'private',  # WARNING: this option will soon be removed
}
```
You can look up the available options from `get_default_settings()` in [storages/backends/s3boto3.py](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L279).

**NOTE:** The `''default_acl'` option will be removed with the next release of `django-storages` according to their [CHANGELOG](https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst).
