### ISSUE TITLE
No matching distribution found for django-dbbackup==3.2.0

### ISSUE THREAD

**Issue by Vadorequest** [django-dbbackup/django-dbbackup#286]
I'm getting the following error in my staging environment:

`No matching distribution found for django-dbbackup==3.2.0 (from -r requirements.txt (line 4))`

I don't get it since it worked fine in my local environment.

**Comment by eriktelepovsky** [comment]
Cache issue? Try install using `--no-cache-dir` option:

https://pip.pypa.io/en/stable/reference/pip_install/#caching

**Comment by Vadorequest** [comment]
No idea what the issue was, too long ago. I'm closing it.
