### ISSUE TITLE
CommandConnectorError  mysqldump: Error 2013: Lost connection to MySQL server during query when dumping table 

### ISSUE THREAD

**Issue by noodlebreak** [django-dbbackup/django-dbbackup#288]
Hi,

One of the tables in my DB is very huge, around ~1.4GB in size. Of late, the dumps crontab result in this error while dumping the particular table. And no, it's not data corruption, because the row no. at which the error occurs, changes.

```
CommandConnectorError: Error running:  mysqldump oracle_live --quick --host=mydb.ap-south-1.rds.amazonaws.com --user=xyz --password 
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Error 2013: Lost connection to MySQL server during query when dumping table `auditlog_logentry` at row: 1636212
```

How to solve this? Is this going to be fixed by changing stuff in mysql settings? Like `net_write_timeout` ?

Anyone who has encountered this before, please advise, help.

**Comment by WooDzu** [comment]
Hi @noodlebreak Did you manage to find out what was causing this issue?

**Comment by ZuluPro** [comment]
Are you sure it's a dbbackup error ? `mysqldump: Error 2013` clearly states, this is not.

**Comment by WooDzu** [comment]
I managed to get to the bottom of this. Sorry if this is unrelated to this project but was on the top of search results.

I was doing external backups of mysql 5.6 server using mysqldump shipped with mysql-client-5.7 on Ubuntu 18.
Now running smoothly using mysql-client-5.6 from archive of Ubuntu 16

**Comment by noodlebreak** [comment]
I manipulated the backup command, to skip some tables, as is mentioned in the docs of this project. The tables I skipped were very large in size, and need not be backed up every hour.

**Comment by jonathan-s** [comment]
As this issue seems to be resolved I'm closing this issue.
