### ISSUE TITLE
Inaccuracies in the documentation

### ISSUE THREAD

**Issue by mtazzari** [django-dbbackup/django-dbbackup#296]
Many thanks for this useful package! I'd like to point out two typos in the docs:

1) the help of the [`mediabackup` command](https://django-dbbackup.readthedocs.io/en/stable/commands.html#mediabackup) reports:
```bash
 -z, --compress        Do not compress the archive
```
which should be
```bash
 -z, --compress        Compress the archive
```
I have just tested it, and this option actually produces `.tar.gz` files.

2) in the installation instructions [Add it in your project](https://django-dbbackup.readthedocs.io/en/stable/installation.html#add-it-in-your-project), this line
```py
DBBACKUP_STORAGE = 'dbbackup.storage.filesystem_storage'
```
gives error:
```bash
AttributeError: module 'dbbackup.storage' has no attribute 'filesystem_storage'
```
while this [SO answer ](https://stackoverflow.com/questions/39190646/what-the-right-setting-for-django-dbbackup) provides a working solution:
```python
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
```
and in fact the mistake in the docs was already pointed out there.

Just reporting this, it'd be helpful to have this fixed in the docs. Thanks!

**Comment by jonathan-s** [comment]
All of these issues are fixed.
