### ISSUE TITLE
Feature: exclude some folders while using mediabackup

### ISSUE THREAD

**Issue by adi-** [django-dbbackup/django-dbbackup#300]
An option to exclude specified folders in Django's media would be nice.

**Comment by jonathan-s** [comment]
Requested by two other people in #45

**Comment by ZuluPro** [comment]
Hi @jonathan-s 
I think @adi- requests **NOT** exclude.

Hi @adi- 
Can expose why you would need too not exclude ?

**Comment by adi-** [comment]
My mistake. Fixed.

**Comment by jonathan-s** [comment]
Ah right, then I'll close this and open the other issue again.
