### ISSUE TITLE
Table 'foo_bar' already exists

### ISSUE THREAD

**Issue by stephenfin** [django-dbbackup/django-dbbackup#311]
I've been heavily using `django-dbbackup` with a MySQL database as part of my development workflow, particularly for use with migrations. I've noticed that if I'm working on a migration that adds a new table and try to use `dbrestore` to restore a backup from before this migration, the `dbrestore` command doesn't drop the newly added table. This results in errors like the below:

```
django.db.utils.OperationalError: (1050, "Table 'foo_bar' already exists")
```

I imagine this is more of a feature request than a bug, since I'm not sure we should be dropping all tables by default (though maybe we do just that - I haven't looked at the source yet). However, perhaps we could add a flag to wipe everything before doing the restore?

**Comment by ZuluPro** [comment]
I think you can play with MySQL option to create `CREATE TABLE IF NOT EXIST` statements.
