### ISSUE TITLE
Failing with django 3

### ISSUE THREAD

**Issue by Orangensaft** [django-dbbackup/django-dbbackup#314]
Django 3 removed six from django.utils. This breaks django-dbbackup when using django 3.
```Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vent/backend/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/vent/backend/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/vent/backend/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vent/backend/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/vent/backend/lib/python3.8/site-packages/dbbackup/apps.py", line 15, in ready
    from dbbackup import checks
  File "/home/vent/backend/lib/python3.8/site-packages/dbbackup/checks.py", line 3, in <module>
    from django.utils.six import string_types
ModuleNotFoundError: No module named 'django.utils.six'

**Comment by alexanderoskin** [comment]
The same issue

**Comment by SchrodingersGat** [comment]
Same

**Comment by serranomorante** [comment]
I'm facing this problem too.

**Comment by debdolph** [comment]
Any progress on this?

**Comment by Natureshadow** [comment]
Thanks for keeping support for ancient versions forever :(.

**Comment by undiplomatic** [comment]
Same :/

**Comment by timonweb** [comment]
Hi there, submitted PR #319 , so while waiting for it to be merged you can use my fork from: https://github.com/django-dbbackup/django-dbbackup.git

Just add this line to requirements.txt:

```
git+https://github.com/timonweb-forks/django-dbbackup.git#egg=django-dbbackup
```

**Comment by Natureshadow** [comment]
The change in that PR seems unrelated.

**Comment by Natureshadow** [comment]
So, django-storages supports Django 3.0 now.

Can we get a release?

**Comment by timonweb** [comment]
+1 for a release!

**Comment by umaimehm** [comment]
Workaround until a stable release for Django 3 is laumcnhed:

Navigate into the virtual python env and search for string "django.utils.six"

You will probably get these files if the string is found:
env/lib/python3.8/site-packages/dbbackup/db/*

In all files, replace "django.utils.six" with string "six"

**Comment by yinhaibo01** [comment]
+1 for a release

**Comment by yhoiseth** [comment]
As a temporary fix, you can probably install the version you need using [this method](https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip).

**Comment by debdolph** [comment]
> As a temporary fix, you can probably install the version you need using [this method](https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip).

Yup, i know. But it isn't really a solution to add git dependencies to a project.

**Comment by yhoiseth** [comment]
How is it not a solution?

**Comment by pulse-mind** [comment]
It is a solution but it creates risk at each delivery on a production server.

**Comment by Natureshadow** [comment]
> How is it not a solution?

Because it will prevent any sane product from deploying in production,
because a sane deployment process will block a production deployment
from untrusted sources, because every added source for dependencies is a
security risk.

**Comment by pytholabsbot1** [comment]
Works man! thanks

**Comment by schostac** [comment]
So when released?

In the meantime, I've used this:

```
find . -path '*site-packages/dbbackup*' -iname '*.py' | tr '\n' '\0' | xargs -0 sed -i 's/django\.utils\.six/six/g'
find . -path '*site-packages/dbbackup*' -iname '*.py' | tr '\n' '\0' | xargs -0 sed -i 's/from\ django.utils\ import\ six\,/import\ six\nfrom\ django.utils\ import/g'
find . -path '*site-packages/dbbackup*' -iname '*.py' | tr '\n' '\0' | xargs -0 sed -i 's/from\ django.utils\ import\ six/import\ six/g'
```

**Comment by max-wittig** [comment]
The latest hash works, so we just need a new release. The last one was created **3 years ago**!

It's always sad to see projects, which are active but cannot be used as they don't release on regular basis. What do you think @pkkid @ZuluPro ?

**Comment by ZuluPro** [comment]
@all 
django-dbbackup 3.3.0 has been released on pypy

I'm am sorry for the latency, I didn't realise so much people were using this tool.
Is there anyone interested to be maintainer ?

**Comment by Natureshadow** [comment]
Hi,

>I'm am sorry for the latency, I didn't realise so much people were using this tool.

Thanks, AlekSIS reintroduced dbbackup tonight and the new release works great!

>Is there anyone interested to be maintainer ?

As we strongly depend on the ecosystem, helping you woth maintenance task would be something I could do.
