### ISSUE TITLE
Integration with   django-tenant

### ISSUE THREAD

**Issue by EngFarisAlsmawi** [django-dbbackup/django-dbbackup#315]
Test with django tenant not worked.

details:

> 
> Traceback (most recent call last):
>   File "manage.py", line 21, in <module>
>     main()
>   File "manage.py", line 17, in main
>     execute_from_command_line(sys.argv)
>   File "F:\raqone\raq\.env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "F:\raqone\raq\.env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "F:\raqone\raq\.env\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "F:\raqone\raq\.env\lib\site-packages\django\core\management\base.py", line 369, in execute
>     output = self.handle(*args, **options)
>   File "F:\raqone\raq\.env\lib\site-packages\dbbackup\utils.py", line 117, in wrapper
>     func(*args, **kwargs)
>   File "F:\raqone\raq\.env\lib\site-packages\dbbackup\management\commands\dbbackup.py", line 58, in handle
>     self.connector = get_connector(database_key)
>   File "F:\raqone\raq\.env\lib\site-packages\dbbackup\db\base.py", line 39, in get_connector
>     **connector_path = connector_settings.get('CONNECTOR', CONNECTOR_MAPPING[engine])
> KeyError: 'django_tenants.postgresql_backend'**
>

**Comment by jonathan-s** [comment]
This is a fairly specific ask which wouldn't benefit the majority of users at dbbackup. I'd be open to implement this against a commission though.

**Comment by JasurbekNURBOYEV** [comment]
You can use already-implemented PostgreSQL connector for django-tenants. Simply put connector mapper in your settings.py as below:

```
DBBACKUP_CONNECTOR_MAPPING = {
    'django_tenants.postgresql_backend': 'dbbackup.db.postgresql.PgDumpConnector'
}

```

You don't actually have to use `dbbackup.db.postgresql.PgDumpConnector`, but this is a default one for PostgreSQL. There is `dbbackup.db.postgresql.PgDumpBinaryConnector` too, please refer to [docs](https://django-dbbackup.readthedocs.io/en/master/databases.html#postgresql) for more info.
