### ISSUE TITLE
setting DBBACKUP_MEDIA_PATH  not used

### ISSUE THREAD

**Issue by patroqueeet** [django-dbbackup/django-dbbackup#322]
when I check the code of v3.2.0:

```
$ grep -Ir MEDIA_PATH .ve/lib/python3.7/site-packages//dbbackup/
.ve/lib/python3.7/site-packages//dbbackup/settings.py:MEDIA_PATH = getattr(settings, 'DBBACKUP_MEDIA_PATH', settings.MEDIA_ROOT)
```

it does not find this setting to be used anywhere. can that be?

**Comment by mjlabe** [comment]
You have `//dbbackup/`. Is that a typo or the problem?

**Comment by jonathan-s** [comment]
Yeah, it seems like it's actually not used anywhere..

**Comment by mbaechtold** [comment]
This is a problem. When I run `python manage.py mediabackup` it puts my whole project into the tarball, not only the media folder. Furthermore this fails if there are symlinks within your projects.

**Comment by patroqueeet** [comment]
> You have `//dbbackup/`. Is that a typo or the problem?

grmpf. my bad:

```
(.ve) darg@das-aktienregister:~/darg$ grep -Ir MEDIA_PATH .ve/lib/python3.7/site-packages/dbbackup/
.ve/lib/python3.7/site-packages/dbbackup/settings.py:MEDIA_PATH = getattr(settings, 'DBBACKUP_MEDIA_PATH', settings.MEDIA_ROOT)
.ve/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py:            self.media_storage = get_storage_class()(location=settings.MEDIA_PATH)```
