### ISSUE TITLE
dbrestore database_name problem

### ISSUE THREAD

**Issue by schostac** [django-dbbackup/django-dbbackup#325]
In settings, I've got `default` and `documents` databases. I run `python manage.py dbrestore --database=documents` and get an error (not important here) mentioning `default` database despite otherwise specified. 

I looked into `get_connector` in `dbbackup/db/base.py `and indeed the wrong database name is passed. Then in `dbbackup/management/commands/dbrestore.py` I found `self.connector = get_connector('default')`. However, on master I see that the line is gone and instead there is `get_connector(self.database_name)`.

So, was there an issue or it still persists? If it was fixed, when released? I'm using `django-dbbackup 3.2.0`.

**Comment by jonathan-s** [comment]
So it's been fixed in master, but the latest release (3.2.0) still contains the line `self.connector = get_connector('default')`.

**Comment by jonathan-s** [comment]
@schostac if you follow the issue #350, I'll close that issue once we've made a new release.
