### ISSUE TITLE
Special Characters like *, # not allowed

### ISSUE THREAD

**Issue by maqib10** [django-dbbackup/django-dbbackup#334]
Hi, I am using this package **V3.3** to backup my database. I am having special characters in db password. This package takes only abcd@123 not taking abcd*#123@45. When I removed * and # from the password. This runs. Could you tell me which special characters this application will take?
Or if you consider this as bug please resolve this and update.

**Comment by jonathan-s** [comment]
Should be fixed in #361, if you have any issues in current master let me know and we'll sort this out.
