### ISSUE TITLE
Typo in tox

### ISSUE THREAD

**Issue by jonathan-s** [django-dbbackup/django-dbbackup#345]
https://github.com/django-dbbackup/django-dbbackup/blob/master/tox.ini#L55

**Comment by johnthagen** [comment]
I don't think that is a typo: https://pypi.org/project/djongo/

The test env is for testing MongDB, and that package is for: "Use Mongodb as a backend database for your django project, without changing a single django model"

**Comment by jonathan-s** [comment]
Well what do you know 😅
