### ISSUE TITLE
password authentication failed for user

### ISSUE THREAD

**Issue by mjlabe** [django-dbbackup/django-dbbackup#347]
When I try to backup a Postgres database, I get the following error:

`pg_dump: [archiver (db)] connection to database "my_db" failed: FATAL:  password authentication failed for user "my_db"`

Even though the password is set, the command still uses --no-password.

I have tried using DBBACKUP_CONNECTORS and not, but it still can't authenticate.

```
DBBACKUP_CONNECTORS = {
    'default': {
        'USER': os.getenv('DATABASE_USER', 'al'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', None),
        'HOST': os.getenv('DATABASE_HOST', 'db')
    }
}
```

Why is the command sent without a password (`pg_dump  --host=db --port=5432 --username=my_user --no-password --clean my_db `)?

**Comment by mjlabe** [comment]
Looks like I need to create a pgpass file.

**Comment by iAnanich** [comment]
Solution with `pgpass` file seems bad, because on server it would be really insecure, and even worse if using containers.

**Comment by mjlabe** [comment]
Why? Worse than an environment variable? Is there an alternative solution?

**Comment by iAnanich** [comment]
In case of docker containers, env vars are really not secure, there is a security vulnerability discovered.
`pgpass` file could end up in docker image which leads to database password being leaked.
Docker has a solution like Docker Secrets, which uses files but in a bit different way - they are encrypted unless connected to a container, they are immutable and won't be ever end up in Docker Image. This is why I'm moving my stacks from using common `.env` to Docker Secrets for sensitive data and all other variables being set from GitLab CI Variables.

**Comment by iAnanich** [comment]
the point of my "pgpass solution is bad" comment is that `django-dbbackup` should NOT rely on it, or any other file, except it's Docker Secrets file.

**Comment by mjlabe** [comment]
Wouldn't you just mount the file just like env files? It doesn't seem less secure than env files and seems more secure than environment variables.
