### ISSUE TITLE
Options --encrypt and --compress doesn't work together

### ISSUE THREAD

**Issue by Fraterius** [django-dbbackup/django-dbbackup#35]
It would be nice if those options could be used together, it'd be useful for large databases that needs some protection or if one would like to send big backup over unencrypted medium like email.

Right now the output of python manage.py dbbackup --encrypt is the same as python manage.py dbbackup --compress --encrypt.

**Comment by benjaoming** [comment]
Option should also be universal whether it's database or media files.

**Comment by ZuluPro** [comment]
Do you still have this bug, unit test seems to valid this?

**Comment by Fraterius** [comment]
Yup it looks like it's fixed in 2.0.5a0 version. If anyone else feels otherwise please let me know. Thanks for the great job.
