### ISSUE TITLE
ERROR:  role "rdsadmin" does not exist

### ISSUE THREAD

**Issue by 24thDawn** [django-dbbackup/django-dbbackup#358]
I got this while trying to restore an aws backup locally.

`dbbackup.db.exceptions.CommandConnectorError: Error running:  psql  --host=localhost --port=5432 --username=postgres --no-password --set ON_ERROR_STOP=on --single-transaction proddb2
ERROR:  role "rdsadmin" does not exist`

Is there a way to resolve this?

**Comment by jonathan-s** [comment]
Have you tried to create the rdsadmin role locally? https://www.postgresql.org/docs/13/database-roles.html

**Comment by 24thDawn** [comment]
I created the role locally using pgAdmin and it worked perfectly, thank you!

**Comment by jonathan-s** [comment]
Glad to hear.
