### ISSUE TITLE
Exclude some tables data from backup

### ISSUE THREAD

**Issue by KessoumML** [django-dbbackup/django-dbbackup#374]
# Feature Request

Hi, 
Sometimes doing migration to newer version of applications we have to make sure about every aspect of data integrity, in some cases there are tables generated by automations tools which we don't need to backup, so we need to exclude these tables when we use dbbackup because these data will be generated again with automation tools.  

The plugin already support this under the hood but there is no interface exposed to use it from command console.

**Comment by jonathan-s** [comment]
Hi @KessoumML, 
With #363 we merged the ability to exclude backuping the data in the tables for postgres. Is that what you are looking for? I would also like to know what database you are using.

**Comment by KessoumML** [comment]
Hello Jonathan,
Actually yes !, this what I'm looking for, I have read the source code and I found that the --exclude-table-data is already supported. 

I'm using postgres and pg_dump already has the option --exclude-table-data=pattern to exclude tables data but, dbbackup [options] doesn't contain any option to specify this excluded tables data.

I need an interface from dbbackup  (like: dbbackup -x "public.table1, table2") to do the job.

**Comment by jonathan-s** [comment]
The version on pip does not support the above. But if you do ´pip install git+https://github.com/django-dbbackup/django-dbbackup.git` you'd get access to everything on master. 

We'll make a release at the end of the year at the latest so that all the other fixes will currently on master will be released.

**Comment by KessoumML** [comment]
I have forked the repo and added the command to the interface, now I'm using dbbackup -x to exlude tables data.
Please update the readme file in Master by adding the new features
Thank you @jonathan-s , I'm wating for the new release, have a good day.

**Comment by jonathan-s** [comment]
@KessoumML, I had a look at the commit you made to your own repo. If you just submit a PR I'll accept it as is.

**Comment by KessoumML** [comment]
Okay, I'll make a PR, Thank you @jonathan-s
