### ISSUE TITLE
Compressing encrypted files should not be done. 

### ISSUE THREAD

**Issue by jonathan-s** [django-dbbackup/django-dbbackup#377]
# Bug Report

## Describe the bug
As mentioned in this [server fault post](https://serverfault.com/questions/89880/compressing-encrypted-files) you can't compress encrypted files which is what we try to do if use both the compression flag and the encryption flag. 

See https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/management/commands/dbbackup.py#L81-L86

## Expected behavior
Either or needs to be selected, if both are selected we should throw an error so that the user can take a correct decision. Alternatively, which may be a better decision is that we need to compress first, then do an encryption as mentioned here in #292 

### Django-dbbackup
- pypi: 3.3.0

**Comment by johnthagen** [comment]
If you compress *first*, and then encrypt you should be able to have the benefits of both.

**Comment by johnthagen** [comment]
Looking at the code, it looks like this is done in the correct order (compression first, to reduce size, and then encrypt).

**Comment by ZuluPro** [comment]
@jonathan-s @johnthagen
Yes I compress, then encrypt, no issue
