### ISSUE TITLE
Warning in Documentation to wait for 2.0 final

### ISSUE THREAD

**Issue by zerok** [django-dbbackup/django-dbbackup#38]
There is still this warning in the index.rst of the documentation:

> django-dbbackup is currently under heavy refactoring, stay tuned for new versions and a final 2.0 release.

Am I correct in assuming that this is obsolete now that this package is already at 2.0.4? :-)

**Comment by benjaoming** [comment]
Yes, that's my impression, too... people shouldn't be afraid to submit PRs
because of some impending plan to change everything... it's been quite
stable for a while :)
