### ISSUE TITLE
MySQL backups fail due to tablespaces

### ISSUE THREAD

**Issue by HowManyOliversAreThere** [django-dbbackup/django-dbbackup#395]
# Bug Report

## Describe the bug

MySQL 5.7.31 / 8.0.21 introduced a breaking change to require the `PROCESS` privilege to perform `mysqldump`s that include tablespaces. A combination of the `--no-tablespaces` flag and setting `--column-statistics=0` can be added to circumvent the need for this `PROCESS` privilege, however there is no interface to django-dbbackup to allow this to happen, preventing users who do not have access to the required privilege from being able to perform database backups.

## To Reproduce

1. Run a MySQL 8.0.21+ server
2. Restore some data into it via `dbrestore`
3. Attempt to dump the data back out via `dbbackup`, with a user account lacking the `PROCESS` privilege

## Expected behavior

`dbbackup` should successfully complete without throwing any of the following errors:
- `mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces`
- `mysqldump: Couldn't execute ...: Unknown table 'COLUMN_STATISTICS' in information_schema (1109)`

### Django-dbbackup
- pypi: 3.3.0

### External tools
- Python: 3.8.5
- Django: 3.2.6
- OS: Linux

**Comment by HowManyOliversAreThere** [comment]
Issue was ultimately resolved by simply utilising the `DUMP_SUFFIX` connector parameter, by adding the following to my Django settings:

```py
DBBACKUP_CONNECTORS = {
    'default': {
        'DUMP_SUFFIX': '--no-tablespaces --column-statistics=0',
    }
}
```

**Comment by stephenfin** [comment]
fwiw, you'll see a similar issue if you use `mariadb-server` with `mysql-client`. This is easily fixed by replacing `mysql-client` and `libmysqlclient-dev` with `mariadb-client` and `libmariadbclient-dev` (or your distro equivalent packages)
