### ISSUE TITLE
ugettext_lazy breaks with Django 4.0 alpha 1 release

### ISSUE THREAD

**Issue by awtimmering** [django-dbbackup/django-dbbackup#399]
Can a release be made including #342 (replace `ugettext_lazy` with `gettext_lazy`)?

The newly released [Django 4.0 alpha 1](https://www.djangoproject.com/weblog/2021/sep/21/django-40-alpha-1-released/) has dropped `ugettext_lazy`.
The latest release of django-dbbackup still uses `ugettext_lazy`. This was addressed in #342 however not yet released, meaning of dbbackup run into errors and can not try their applications on Django 4.0 alpha 1 until this is done.

**Comment by johnthagen** [comment]
Related to #381

**Comment by johnthagen** [comment]
Should also include wheels in the next release& #382

**Comment by johnthagen** [comment]
If @jonathan-s is no longer maintaining this project, there may need to be a new community fork. There have been no commits for a year.

**Comment by pulse-mind** [comment]
> If @jonathan-s is no longer maintaining this project, there may need to be a new community fork. There have been no commits for a year.

May be @jonathan-s can give us is idea about that ? 

I'm interesting by going forward on this subject

**Comment by johnthagen** [comment]
@pulse-mind Probably what needs to happen is someone volunteers to fork, merges in the necessary 4.0 compatibility patches, and publishes under an available name on PyPI such as `django-dbbackup2`. We can then advertise the fork on the issues in this repo to make it more discoverable. To be a "friendly" fork, we offer to merge changes back to `django-dbbackup` if maintainers re-appear or are willing to add new maintainers.

**Comment by pulse-mind** [comment]
@johnthagen why using a fork, it would be better to have the rights on the repo to do the job?!?
Then it would be possible to accept push requests, release versions...
I do not know how to publish on PyPi, if it is automatic when we create a version...?

**Comment by johnthagen** [comment]
> why using a fork, it would be better to have the rights on the repo to do the job?!?

Ideally yes, but if the maintainers are not responsive, there is no one to grant anyone new permissions to this repo.

**Comment by pulse-mind** [comment]
> > why using a fork, it would be better to have the rights on the repo to do the job?!?
> 
> Ideally yes, but if the maintainers are not responsive, there is no one to grant anyone new permissions to this repo.

Agree with you. 
We can let one week to @jonathan-s to answer ? 

May be some others users like @ZuluPro may know something ?

Is it possible to know the list of the members who have this kind of permissions ?

**Comment by ZuluPro** [comment]
Hi everyone,
I'm sorry for my absence and my late reply.

I absolutely don't have the time to maintain DBBackup but it would be a pleasure to pass the ownership to someone with more time and knowledge.

Who's volunteer to maintain DBBackup ?

**Comment by johnthagen** [comment]
I have enough time to do very basic maintenance (keep dbbackup working on latest Django / remove deprecation warnings / etc.) I'm currently doing the same for [`django-solo`](https://github.com/lazybird/django-solo).

If you also want to grant ability to upload to PyPI my username there is: https://pypi.org/user/johnthagen/

**Comment by pulse-mind** [comment]
Thank you @johnthagen !! If you need help, let me know!

**Comment by Archmonger** [comment]
Hey @ZuluPro 

I'm coming over from the [Jazzband](https://github.com/jazzband) GitHub organization.

I would be interested in taking temporary ownership for this repo and doing the necessary changes to get it maintained by the org.

There are various members that I'm sure would support maintenance for this repo within Jazzband.

**Comment by ZuluPro** [comment]
Hi @Archmonger 
Yes Jazzband iis a good idea, I think a bit of maitenance and cleaning should be good before submit Dbbackup.

Hi @johnthagen 
Thank you for you time and attention,
I give you the rights for the Github Organization and the the Pypi repo.

But like @Archmonger suggested, it could be a good thing to transfer it to Jazzband

**Comment by johnthagen** [comment]
I also agree Jazzband would be a very good long term plan.

Thanks @ZuluPro!

**Comment by Archmonger** [comment]
> I also agree Jazzband would be a very good long term plan.
> 
> Thanks @ZuluPro!

Let me know if you need any support on this!

**Comment by ZuluPro** [comment]
Hi @Archmonger 
Can you contact me on my mail box anthony.monthe[a]gmail.com ??
So I can give you grants on Pypi

**Comment by johnthagen** [comment]
I'm currently working on cleaning things up for a release.

> Let me know if you need any support on this!

I think another issue with a checklist of what needs to be done to get this repo ready for submission to JazzBand, would be very helpful.

**Comment by johnthagen** [comment]
@ZuluPro I'm pulling together a `4.0.0b0` release that I'd like to push to PyPI for people to test out. I can't seem to upload and when I look at my projects on PyPI, I don't see `django-dbbackup`. I also don't see myself listed as a maintainer at https://pypi.org/project/django-dbbackup/.

Would you mind double checking if I was invited to the PyPI project? I'm also not sure where I would "see" invites. I've looked through all of the pages on my PyPI account and don't see anything about `django-dbbackup`.

My profile: https://pypi.org/user/johnthagen/

**Comment by banagale** [comment]
Bump. @ZuluPro Would you please look in on this?  Django 4.0 is released.

**Comment by Archmonger** [comment]
I have the ability to create releases and will do so once @johnthagen tags a solid build

**Comment by banagale** [comment]
I see, @johnthagen Do you see that @Archmonger is prepared to publish a release?

@Archmonger Can you clarify whether you consider a beta release, like the one @johnthagen mentioned above (`4.0.0b0`) as suitable for publishing on pypi? Or when you say "solid build" do you mean a tag of something that is ready for release?

**Comment by Archmonger** [comment]
I just confirmed that john had not been invited to PyPI, so I've sent him an invite.

I am currently not a maintainer on the GitHub repo though so I'll need @johnthagen to add me as one if I am to tag releases in the future.

**Comment by banagale** [comment]
@Archmonger Thank you for looking at that. I appreciate any further cooperation needed to get a Django 4.0-compatible release out the door.

**Comment by Archmonger** [comment]
As a temporary workaround, you can install pip install via git `git+https://github.com/django-dbbackup/django-dbbackup.git`

ex `pip install git+https://github.com/django-dbbackup/django-dbbackup.git`

**Comment by johnthagen** [comment]
`4.0.0b0` has been released: https://pypi.org/project/django-dbbackup/4.0.0b0/ 🎉 

> I just confirmed that john had not been invited to PyPI, so I've sent him an invite.

Thanks!

> I am currently not a maintainer on the GitHub repo though so I'll need @johnthagen to add me as one if I am to tag releases in the future.

@Archmonger You have been invited as an owner to the `django-dbackup` organization

> I have the ability to create releases and will do so once @johnthagen tags a solid build

`4.0.0b0` has been tagged in GitHub, but as a pre-release it doesn't show up in the main page UI, so it might not have been obvious it had been tagged before: https://github.com/django-dbbackup/django-dbbackup/releases/tag/4.0.0b0

**Comment by phroiland** [comment]
I know this issue is closed, but any word on getting an official release?

Appreciate the beta version.

**Comment by johnthagen** [comment]
Please follow #415. Unfortunately we are still waiting for the original maintainers to give access to the ReadTheDocs site.
