### ISSUE TITLE
Add support for Mongodb

### ISSUE THREAD

**Issue by israfilkara** [django-dbbackup/django-dbbackup#46]
Hello,
This package is very useful for our team. But we are using also mongodb. Are you going to support mongodb.

Thanks.

**Comment by mjs7231** [comment]
There are currently no plans for this, but it's a great idea. I'll look into it.

**Comment by ZuluPro** [comment]
Related to #58. In progress

**Comment by ZuluPro** [comment]
#58 Merged !
