### ISSUE TITLE
Custom filename template not settable for S3?

### ISSUE THREAD

**Issue by mallyvai** [django-dbbackup/django-dbbackup#52]
Set the following variables: 

DBBACKUP_STORAGE
DBBACKUP_S3_BUCKET
DBBACKUP_S3_ACCESS_KEY
DBBACKUP_S3_SECRET_KEY

as well as DBBACKUP_FILENAME_TEMPLATE according to the docs, returning a string. Still seems to be always setting it to default.backup when it ends up in S3, not even timestamped with date/time as the docs say.

I got around it for the time being with a monkeypatch, but it's obviously not ideal.

**Comment by ZuluPro** [comment]
Is this bug still relevant after PR #98 ?
