### ISSUE TITLE
Tutorial needs to show restore example

### ISSUE THREAD

**Issue by mallyvai** [django-dbbackup/django-dbbackup#53]
A great addition to the initial basic tutorial would be an inline restore example in addition to the existing backup example. Backup without restore isn't much of a backup :-)

**Comment by ZuluPro** [comment]
Where can I find this tutorial ? Is this kind of example you're looking for: https://github.com/django-dbbackup/django-dbbackup/blob/master/docs/index.rst#dbrestore
