### ISSUE TITLE
./manage.py dbrestore needs to respect DBBACKUP_STORAGE

### ISSUE THREAD

**Issue by mallyvai** [django-dbbackup/django-dbbackup#54]
I have DBBACKUP_STORAGE set to dbbackup.storage.s3_storage, but ./manage.py dbrestore still is trying to pull from some local 'default.backup' backup file first, instead of the configured S3 bucket.

Note that the backups to S3 work fine.

**Comment by ZuluPro** [comment]
I think this issue is not relevant anymore with merged PR #107 ?
