### ISSUE TITLE
KeyError: 'USER' while using SQLite 

### ISSUE THREAD

**Issue by SG345** [django-dbbackup/django-dbbackup#56]
While using dbbackup and restore commands for backing up an SQLite database, a 'KeyError: 'USER'' error is shown.
There's no USER in settings.DATABASES as it is an optional setting in SQLite.

**Comment by benjaoming** [comment]
I'll have a look at this

**Comment by ZuluPro** [comment]
I think this issue is fixed with this PR #66 .

**Comment by benjaoming** [comment]
Yes, that looks like the fix that was needed, thanks for looking through issue history and keeping it updated!

@SG345  this should fix the issue. I don't know when a release is coming up, should be soon
