### ISSUE TITLE
Fallback storage

### ISSUE THREAD

**Issue by rblack** [django-dbbackup/django-dbbackup#61]
This is not a bug actually, but a suggestion to make dbbackup more "backupier" :)
In case of failing saving backup to storage, backup file will be lost. For example, dropbox api sometimes gives 500 error and no files will be saved. To prevent this fallback storage could be used and settings changed to something similar to Django's database setttings:

```
DBBACKUP_STORAGES = {
    'default': {
        'MODULE': 'dbbackup.storage.dropbox_storage',
        'TOKENS_FILEPATH': '<local_tokens_filepath>',
        'APP_KEY': '<dropbox_app_key>',
        'APP_SECRET': '<dropbox_app_secret>',
    },
    'fallback': {
        'MODULE': 'dbbackup.storage.s3_storage',
        'BUCKET': '<amazon_bucket_name>',
        'ACCESS_KEY': '<amazon_access_key>',
        'SECRET_KEY': '<amazon_secret_key>',
    }
}
```

May be also add optional arg to manage.py command to restore either from default or fallback storage:
python manage.py dbrestore fallback

As a simpler alternative use more than one storage to backup to both everytime.

```
DBBACKUP_STORAGES = ('dbbackup.storage.dropbox_storage', 'dbbackup.storage.s3_storage')
```

**Comment by ZuluPro** [comment]
@rblack 
I think the idea of make redundancy with storage is bad. It means we'll have to deal with several storages for list, filter or make operations with backups.
@mjs7231 and @benjaoming may correct me.

But use several storages could be useful for implement archives. Examples:
- Store backups locally, archive them with DropBox
- Store backups on S3, archive them with Glacier

**Comment by Braintelligence** [comment]
Is it possible to store on multiple storage locations regardless of success, though?

**Comment by jonathan-s** [comment]
Closing this, we can keep the discussion in #235
