### ISSUE TITLE
Add logger

### ISSUE THREAD

**Issue by ZuluPro** [django-dbbackup/django-dbbackup#67]
Add loggers and replace all print statements by it.
I think debug log should greatly help us.

**Comment by benjaoming** [comment]
Agreed!

**Comment by ZuluPro** [comment]
I removed `TODO.md` and this task was in since 17th may 2014: https://github.com/django-dbbackup/django-dbbackup/blob/5bb44b8a7ca4ae4bb973a88b44cf938431a88795/TODO.md

There is:
`Use logging instead of print()`

And I think this line is related too:
`Make a proper filesystem log and email that instead of the failure emails`

**Comment by benjaoming** [comment]
Yes, that line is related to log handlers. You can define those in the main django settings.

**Comment by ZuluPro** [comment]
Can be closed, related to PR #118.
