### ISSUE TITLE
Be explicit about django version support

### ISSUE THREAD

**Issue by benjaoming** [django-dbbackup/django-dbbackup#69]
Just added `django>=1.5` to requirements.txt, however it's unsure if this is actually the current state of things. I think we should start by stating which Django versions we want to support and then express that in our requirements and in a tox.ini

**Comment by ZuluPro** [comment]
I don't think it's a great idea to add django in requirements. This is a django third app, so it's obvious.

Same for the fixed test_requirements in setup.py, it should be open a test-requirements.txt.

For django version support, we should support 1.5 and + (as you wrote) for allow old version to backup before upgrade. But version must not be hard written, tox (or Travis) have to make version matrices including supported Python and django versions. For Python versions: 2.7, 3.2, 3.3, 3.4 and pypy.
