### ISSUE TITLE
django-dbbackup + celery

### ISSUE THREAD

**Issue by psychok7** [django-dbbackup/django-dbbackup#95]
Hi there, i am trying to figure out how can i use `django-dbbackup` with `celery` without having to invoke the management command from inside a task. Something like importing a function or a few functions keeping my `runserver --settings=blabla` that is already in use.

**Comment by benjaoming** [comment]
@psychok7 

What's wrong with `call_command('dbbackup', option=value)`...?

**Comment by psychok7** [comment]
@benjaoming i did not know this command, thanks
